### ISSUE TITLE
Use YAML instead of HCL or JSON

### ISSUE THREAD

**Issue by josephpratt** [hashicorp/hcl#151]
HCL is a bad idea... Coming from a JSON/XML-only (read .NET) world, I've found YAML to be straight-forward with a shallow learning-curve. Why not unify Hashicorp's config languages under YAML?

The "Why" in the readme is a paper-thin reason to create a brand-new config language. It is just another [standard](https://xkcd.com/927/) that will only add to the confusion. If beginners have a hard time with YAML, then why not just make better documentation?

I believe that Hashicorp and their users would only benefit from using a well-known config language across all products. It would make overall entry into the existing Hashicorp suite easier and faster. A familiar structure and syntax would also quickly communicate the semantic of a new Hashicorp product, which would only aid faster adoption.

**Comment by jefferai** [comment]
HCL is fully JSON compatible, so those wishing for familiar structure and syntax are already well-supported!

HCL is simply a relaxation of JSON to allow more human-friendly management.

**Comment by mitchellh** [comment]
Hey @josephpratt,

To add a bit more color as well, I'll respond. 

First off, HCL is not attempting in any way to be a "standard." I've seen the XKCD comic you've linked and enjoy it greatly. HCL's lack of standardization is in the name itself: it is the _HashiCorp_ configuration language. As a standards compliant interop, we've opted to make HCL compatible with JSON. _That_ is the standard we're aligning with, not the HCL that human's edit.

In addition to that, we've actually heard great, great feedback on HCL from users and customers alike. Of course, we do get some feedback that people would prefer this or that, but overall the feedback has been very positive. For those that want to use a standard format, they've been very happy and have praised us on our JSON support.

On YAML in particular: as long as I am at HashiCorp, no HashiCorp tool will use YAML. We may in some form (for example Vault outputs YAML for some commands) in order to interact with other tooling, but YAML will never be a primary input mechanism to HashiCorp tooling. YAML fails in usability for me. If you show a novice a relatively complex YAML configuration, they will not know the _actual_ structure most of the time ("is it an array of hashes, or maybe a hash with a single list?" etc. is common). YAML is a very powerful configuration langauge -- no doubt -- but luckily we have N other standards to choose from and we chose JSON. 😄 

In your case, I recommend sticking with JSON if you're averse to our language.

**Comment by boltronics** [comment]
@mitchellh From the docs:

> Prior to HCL, the tools we built at HashiCorp used a variety of configuration languages from full programming languages such as Ruby to complete data structure languages such as JSON. What we learned is that some people wanted human-friendly configuration languages and some people wanted machine-friendly languages.
> 
> JSON fits a nice balance in this, but is fairly verbose and most importantly doesn't support comments.
> 

How is JSON a nice balance when it doesn't support comments? That's such a nutty thing to say! And then to say YAML fails in usability - which unlike JSON is specifically designed to be human readable...

I've worked with configuration management for many years which is all in YAML, so I've seen a lot of it. Even as a beginner, I can't remember ever looking at something and thinking "I can't tell what data structure this represents". If a novice didn't understand, you could have instead made better documentation to address what you see are the issues (as the OP already pointed out).

It's also not hard to paste some YAML into something like https://www.json2yaml.com/ (which was just the first converter I found when I did a search). If a tool like that didn't exist at the time, you could have better served everyone by making one.

To recommend the OP stick with JSON after he explained he already transitioned away from that to YAML was a but much. I'm sure HCL is much nicer than JSON because HCL (unlike JSON and XML) is designed to be human readable/writable just like YAML is. I can't imagine it would be worse! The frustration is that it's just one more format you're forcing upon everyone.

Those are my opinions anyway. After discovering this repository when reading about Vault, I just came here to open this very issue only to discover it's already a known issue.

**Comment by aescolastico** [comment]
> To recommend the OP stick with JSON after he explained he already transitioned away from that to YAML was a but much. 

How is that a bit much? The alternative would be for a massive corporation like Hashicorp to bend to the whim of a single user and ditch HCL for YAML. Something they spent a lot of time building and works well for their users. OPs request wasnt a reasonable one to begin with. It wasnt even really a request. It was more of rant. Id say @mitchellh response was appropriate.

**Comment by impredicative** [comment]
> How is that a bit much? The alternative would be for a massive corporation like Hashicorp to bend to the whim of a single user and ditch HCL for YAML.

aescolastico, there are two lies in your post. First, the request of YAML is not by a single user alone. Numerous users would like to see it happen, including many who are following this thread. Second, it is not necessary to ditch HCL to support YAML, as both can perhaps be supported. There is also the misleading assertion that because HCL works, YAML is unnecessary. By this faulty logic, one could've argued that JSON theoretically works, and so HCL is unnecessary. As as aside, does anyone even natively use HCL outside of using Hashicorp tools?

**Comment by aescolastico** [comment]
@impredicative I obviously wasnt suggesting only one person would like to see YAML adopted by Hashicorp. Im aware that plenty of people like it. Im just saying that it's not a good reason for Hashicorp to make that huge pivot in product design. 
Also OP literally wrote "Use YAML _instead_ of HCL or JSON". That word is self explanatory. He argued that HCL doesnt even need to exist. So no that wasnt a lie.

**Comment by boltronics** [comment]
To be fair, it didn't need to exist at one point. Now it needs to exist to continue supporting the people who are already using it.

YAML's not perfect (no solution is), but since someone said "as long as I am at HashiCorp, no HashiCorp tool will use YAML", I eventually decided that it's pointless to even try to argue with that kind of stubbornness.

**Comment by apparentlymart** [comment]
Hi all,

This is a really old issue that was closed years ago, and this new discussion doesn't seem to really be adding anything new to it, so I'm going to lock this issue. If there is a specific piece of software you are using that supports HCL but not YAML and you'd like to lobby for it to support YAML either instead of or in addition to HCL then it'd be better to have that discussion within the context of that project, not in this repository.
