### ISSUE TITLE
Pass Multi-Line variable to template file

### ISSUE THREAD

**Issue by Timboo89** [hashicorp/hcl#188]
### Expected behavior
Input File as a String with multiline masking.

### Actual behavior
Just a string without multiline masking. So does it gets interpreted as commands.

### Steps to reproduce
```liquid
data "template_file" "template" {
  template = "${file("${path.module}/setup.sh")}"
  vars {
    httpd_conf = "${file("${path.module}/httpd.conf")}"
  }
}
```

The httpd.conf file contains more than one line. If I use ${httpd_conf} in my setup.sh file, it will be parsed into more than one line too, but I want to echo it like a string.

example:

```
echo ${httpd_conf} > httpd.conf
```

This resolves to:

```
echo here
are
multiple
lines > httpd.conf
```

**Comment by sethvargo** [comment]
Hi @Timboo89 

Thank you for opening an issue, and I'm sorry this is causing you problems. I don't think this is an HCL bug, since HCL has no way of knowing how the underlying template is going to use the data. I think you probably want to use `cat` instead of `echo` here.

```bash
cat > httpd.conf <<EOF
${httpd_conf}
EOF
```

This is much more robust, as you won't have to worry about escaping quotes, etc. Additionally, if you want to disable interpolation of bash arguments (if your conf file has `$VAR`s in it, but you want them to be literally printed instead of interpolated), you can surround the first "EOF" with quotes:


think you probably want to use `cat` instead of `echo` here.

```bash
cat > httpd.conf <<"EOF"
${httpd_conf}
EOF
```

**Comment by mitchellh** [comment]
This is correct. Thanks for reporting this here but HCL actually isn't even involved with the loading of the file. That is a separate process (HIL) once the HCL has already been parsed.

For TF: the `file` will read it as is. You can use the string replacement functions if you want to replace newlines and flatten it.

**Comment by Timboo89** [comment]
Thanks a lot! That's what I need.
For everyone who is interested, that's my simplified solution to replace specific "variables" in that parameter file:

httpd.conf
```
<Directory $${PATH_APACHE_FILES}/>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Order allow,deny
    allow from all
</Directory>
``` 

actual shell script (user_data):
```
sed \
  -e "s|\$\$${PATH_APACHE_FILES}|$${PATH_APACHE_FILES}|g" \
> /etc/httpd/conf.d/apache.conf \
<<"EOF"
${httpd_conf}
EOF
```
