### ISSUE TITLE
Q: Simple JSON nested object to HCL

### ISSUE THREAD

**Issue by mgutz** [hashicorp/hcl#192]
What is the HCL equivalent of this JSON?

```json
{
    "hcl": { "key": 1 }
}
```

I try this

```hcl
hcl = {
   key = 1
}
```

And get 

```json
{
  "hcl": [{"key": 1}]
}
```

**Comment by sethvargo** [comment]
Hi @mgutz 

Thank you for opening an issue. HCL parses this way because it's possible to have multiple objects like this:

```hcl
hcl {
  key = 1
}

hcl {
  key = 2
}
```

In this case, _which_ `hcl` block would win? There is no HCL equivalent JSON in your case. You can either flatten the HCL into a single object at parsing, or alter your program to handle an array of objects instead of a single object.

Hope this helps!

**Comment by mgutz** [comment]
The README says "fully compatible" with JSON. Maybe that should be changed. 

I was aware of the block case. I thought explicitly using assignment `=` might do what I want as opposed to treating it as a repeatable block.

**Comment by sethvargo** [comment]
Hi @mgutz 

It is fully-compatible. That HCL maps directly to JSON.

**Comment by rwiggins** [comment]
If you're here because of Consul's HCL config, which at the time of writing is not really documented, it looks like Consul has some code to manually patch up the above behavior, see [here](https://github.com/hashicorp/consul/blob/c8db140ff752ec4c29d351f1ffae99cef15bcb83/agent/config/config.go#L57). 

That ends up translating

```
performance {
    raft_multiplier = 1
}
```

which normally in HCL corresponds to

```
{
    "performance": [{
        "raft_multiplier": 1
    }]
}
```

into (for Consul specifically)

```
{
    "performance": {
        "raft_multiplier": 1
    }
}
```
