### ISSUE TITLE
Cannot use ternary conditionals with lists

### ISSUE THREAD

**Issue by majoras-masque** [hashicorp/hcl#223]
### HCL Template
```hcl
ec_repl_group_subnet_ids = ["${module.data_sources.environment == "prod" ? [] : module.data_sources.private_subnets_list}"]
```

### Expected behavior
What should have happened?
If environment == "prod" then it should assign an empty list to the ec_repl_group_subnet_ids, else it should assign the list in private_subnets_list. 

### Actual behavior
What actually happened?
Failed with error:
Error: module.postgres_rds_instance.var.rds_cidrs_ingress: At column 3, line 1: conditional operator cannot be used with list values in:

${module.data_sources.environment == "prod" ? [] : module.data_sources.remote_login_cidr_list}

### Steps to reproduce
1. Create a ternary conditional to assign a list value (false = blank list, true = some populated list).  You'll see ternary conditionals only work with strings not lists. I believe you also cannot use it to populate a list with string inputs e.g. ["${env == "prod" ? var.something : var.something_else}"] 
2.
3.

### References
Are there any other GitHub issues (open or closed) that should
be linked here? For example:
- GH-1234
- ...

**Comment by ocervell** [comment]
This is still an issue to this day

**Comment by awichmann-mintel** [comment]
Any update on this? Is this coming with v0.12?

**Comment by apparentlymart** [comment]
This is not a HCL issue... the interpolation syntax is implemented in [HIL](https://github.com/hashicorp/hil), not HCL. So that other repository would be the right place to track this issue, though the HIL behavior is largely frozen at this point so there are no plans to change the conditional behavior for it.

If by "v0.12" you mean _Terraform_ v0.12 (this is not the Terraform repository): Terraform v0.12 no longer uses the older HCL implementation in this repository or HIL. It uses [HCL 2](https://github.com/hashicorp/hcl2) instead, which is currently in a separate repository but [will eventually merge in here](https://github.com/hashicorp/hcl/wiki/HCL-2.0-Transition) once the Terraform team has finished releasing Terraform v0.12 and thus has some spare time to do repository refactoring. HCL 2 incorporates the previously-separate HIL use-cases into a single language, and has a fully-general conditional operator.

The way for applications other than Terraform to get a fully-general conditional operator is to move to using HCL 2 instead of HCL 1 and HIL.

With all of that said: for various reasons this particular issue no longer applies (it's in the wrong repository, it won't be fixed even in the _right_ repository because it's frozen, and HCL 1 and HIL's successor doesn't have this limitation) and so I'm going to close this out.

**Comment by awichmann-mintel** [comment]
That all makes sense. Thank you @apparentlymart
