### ISSUE TITLE
Get AST file for terraform file

### ISSUE THREAD

**Issue by zunlihu** [hashicorp/hcl#250]
I want to parse terraform files(.tf) and save the AST file. Then what should I do?
I am not familiar with golang...
Anyway, thanks a lot.

**Comment by apparentlymart** [comment]
Hi @zunlihu,

In the next major release Terraform will switch away from this version of HCL to [the next-generation version](https://github.com/hashicorp/hcl2), at which point the parser in this repository will no longer be able to read some Terraform configurations.

HCL (regardless of version) is just low-level syntax, and so if your intent is to extract Terraform-related information such as resources, module calls, etc it is probably at to low an abstraction level to be helpful to you, particularly if you are new to Go. I'd encourage you instead to share more details about your use-case in an issue in [the Terraform repository](https://github.com/hashicorp/terraform), and then the Terraform Core team (of which I'm a member) can consider ways to meet your use-case that may be more convenient for you.

Since this is really a Terraform request, and Terraform will no longer use this version of HCL after the next major release, I'm going to close this.
