### ISSUE TITLE
Question about slash escape

### ISSUE THREAD

**Issue by gaoxinge** [hashicorp/hcl#282]
### Code

```go
package main

import (
	"github.com/hashicorp/hcl"
	"fmt"
)

func main() {
	s := "data_dir = \"C:\\Users\\gaoxinge\\AppData\\Local\\Temp\\agent901786071\""
	_, err := hcl.Parse(s)
	fmt.Println(err)
}
```

### Expected behavior

- No error.

### Actual behavior

- Print `At 1:45: illegal char escape`.

### Question

- Does hcl allow the syntax, like the `\\` in string? Because go will merge two slashes into one, the token scanner will raise error when parsing escape.

**Comment by apparentlymart** [comment]
Hi @gaoxinge,

Because both Go and HCL use `\\` as an escape for backslash, you need to escape twice to go through both Go's escaping and HCL's escaping and get literal backslashes.

One way to avoid the double-escaping is to use Go's backtick raw string syntax, like this:

```go
s := `data_dir = "C:\\Users\\gaoxinge\\AppData\\Local\\Temp\\agent901786071"`
```

Go does not interpret escape sequences inside raw strings, so the `\\` sequences in this example will be seen literally by the HCL parser, and HCL will then in turn interpret them as single literal backslash characters.

**Comment by gaoxinge** [comment]
@apparentlymart Thanks.
