### ISSUE TITLE
hclwrite: Block name and label

### ISSUE THREAD

**Issue by dkumor** [hashicorp/hcl#287]
This issue is related to hashicorp/hcl2#23, in that I could not figure out the API in the hclwrite package to perform a modification within a specified existing block.

Suppose the following file:
```
attr1 = "foobar"
service "hello" {
   attr2 = "world"
}
```

I can modify `attr1` by calling `body.SetAttributeValue("attr1",...)`. I can also get the list of blocks in the file by calling `body.Blocks()`.

I cannot, however find any way to tell that the block returned by `Blocks()` is of type "service" with the label "hello", which is where I want to modify `attr2`, if it exists - no such function or struct field seems to be publicly exposed.

I apologize if this is due to me missing some piece of documentation!

**Comment by clarkmcc** [comment]
Do we have an update on this by chance? I noticed the v2 label was added and that the `hcl2` version on godoc is also out.

**Comment by apparentlymart** [comment]
Thanks to hashicorp/hcl2#126, which we merged just before the v2.0.0 release, there are now methods to read the type and labels from a block.

There is not yet a facility to _set_ the type or the labels as I described in my earlier comment. I am not personally working on that right now because my focus is currently elsewhere, but I'd love to review a PR for it if someone else has the time and motivation to work on it, with the methods I described in my earlier comment.

**Comment by bflad** [comment]
I believe this was covered awhile back by https://github.com/hashicorp/hcl/issues/338 and friends as the `hclwrite` exported API now has the following available:

- [`(*hclwrite.Block).Labels()`](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.20.1/hclwrite#Block.Labels)
- [`(*hclwrite.Block).SetType()`](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.20.1/hclwrite#Block.SetType)
- [`(*hclwrite.Block).SetLabels()`](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.20.1/hclwrite#Block.SetLabels)
- [`(*hclwrite.Block).Type()`](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.20.1/hclwrite#Block.Type)

If I am mistaken, please feel free to reach out or reopen this issue. 👍
