### ISSUE TITLE
HCL2 <-> JSON Transformer?

### ISSUE THREAD

**Issue by Aedalus** [hashicorp/hcl#294]
Hi all!

I was wondering if there was anything in the works for a library that could convert HCL2 to JSON and back again, similar to https://github.com/kvz/json2hcl

Thanks!

**Comment by vikas027** [comment]
@PetrusHahol  - I can't seem to install  [pyhcl2](https://github.com/PetrusHahol/pyhcl2) through `pip3`

```bash
$ pip3 install pyhcl2        
ERROR: Could not find a version that satisfies the requirement pyhcl2 (from versions: none)
ERROR: No matching distribution found for pyhcl2
```

[hcl2json]( https://github.com/tmccombs/hcl2json) Go binary recommended by @tmccombs works like a charm on both HCL v1 and v2

**Comment by rulatir** [comment]
### Rulatir's Prophecy

Heed my words: not designing for rigorous bidirectionality from day 0 will be HCL's and terraform's undoing. Within two years starting from now a competing product will emerge, designed from the ground up to support 100% mutually translatable representations for humans and for machines. As a result, its rate of adoption will be 1000% that of terraform's rate of adoption, and it will relegate terraform to obsolescence within another 2 years.

**Comment by mitchellh** [comment]
> not designing for rigorous bidirectionality from day 0 will be HCL's and terraform's undoing

Please note @rulatir that as of Terraform 0.12 (w/ HCL2) there is "rigorous bidirectionality" in the sense that there is an exact 1:1 mapping between JSON and HCL. The issue at hand here is that we don't provide an automated way to do that conversion to/from, which is indeed an open issue.

**Comment by tmccombs** [comment]
> as of Terraform 0.12 (w/ HCL2) there is "rigorous bidirectionality" in the sense that there is an exact 1:1 mapping between JSON and HCL

There is only a 1:1 mapping between JSON and HCL if you know the schema, so you can't really have a general tool to convert between JSON and HCL. Maybe a tool could allow you to specify a schema somehow. But right now the schema is expressed entirely in go code that is tightly coupled to the implementation, and in terraform's case it is even split between terraform itself and individual plugins.

**Comment by jkevlin** [comment]
I agree, the inability to Marshal/Unmarshal TF hcl in go, is a huge negative.  I would not recommend TF for this reason.

**Comment by IvanJosipovic** [comment]
> I agree, the inability to Marshal/Unmarshal TF hcl in go, is a huge negative. I would not recommend TF for this reason.

Agreed

**Comment by apparentlymart** [comment]
Hi all,

This discussion seems to be veering off-topic. It was originally about converting from JSON syntax to native syntax, but recent comments seem to instead be talking about support for programmatically generating Terraform configuration in Go.

As I mentioned before, converting between syntaxes is a concern that would be handled at the application layer, because only the application knows how it intends to interpret the constructs in each syntax. I expect that a shared library could provide some functionality to help applications provide such a mapping in a more convenient way, but that alone would not be sufficient to make inter-syntax conversions available for individual HCL-based languages because each application would need to define its mapping in terms of whatever that is.

If you want to share use-cases for converting between HCL syntaxes in a particular application then I would suggest opening an issue in that application's own repository to advocate for them, and then if one of those application teams decides that such a capability is a high priority for them then they can work with me or one of the other HCL maintainers to design a means to get that done. So far, no team developing an HCL-based application has indicated their intent to support such a thing, and so I have no practical use-cases with which to evaluate potential solutions.

This issue doesn't represent something actionable on its own, so I'm going to close it. If a team working on an HCL-based application wants to pursue something like this, please open a new issue where we can discuss your specific use-cases and produce a suitable technical design with them in mind. Thanks!

**Comment by adrian-gierakowski** [comment]
Given that it’s now possible to convert [HCL to CDKTF](https://developer.hashicorp.com/terraform/cdktf/concepts/hcl-interoperability#cdktf-to-hcl) and back, and that CDKTF can also produce json output, what’s the reason not to support JSON => HCL conversion? Is some information lost when CDKTF is used to generate json (vs hcl)? 

The reason I’d like to be able to do JSON => hcl is that I’m using a tool which generates terraform projects in JSON format and I’d like to produce hcl from its output.

**Comment by apparentlymart** [comment]
Interconversion between CDK for Terraform programs and Terraform language programs is an example of an  _application-layer_ conversion like I was describing in my previous comment.

The system making that conversion is working at the Terraform level of abstraction, and not at the HCL level of abstraction, despite the authors of that documentation incorrectly using the term "HCL" when they ought to have said "the Terraform language".

For example, the code that's supporting part of that functionality includes a function [`renderResource`](https://github.com/hashicorp/terraform-cdk/blob/e922ce570b48c80d6dedf4d76126b77d2ff92517/packages/cdktf/lib/hcl/render.ts#L202-L239), where "resource" is a Terraform-specific concept that HCL alone knows nothing about.

Converting Terraform language native syntax to Terraform language JSON syntax and back is possible in principle, and would require a similar awareness of Terraform-specific concepts to allow the system to correctly understand how to represent a particular JSON input as the equivalent native syntax document.

As I mentioned before, if you want to discuss use-cases for doing that _in the Terraform language_ then the appropriate place to discuss that is in [Terraform's own repository](https://github.com/hashicorp/terraform). If the Terraform team chooses to pursue that then I will help them to evaluate different strategies for doing so.
