### ISSUE TITLE
What is the status of hclwrite and gohcl?

### ISSUE THREAD

**Issue by colinhoglund** [hashicorp/hcl#309]
It looks like the experimental https://github.com/hashicorp/hcl2 repo was archived and partially released here as `v2.0.0`. However, a number of packages seem to be missing, such as `hclwrite` and `gohcl`. Will those eventually make their way into this repo, or should we be using different packages?

FYI, my particular use case is using `hclwrite` for generation/manipulation of blocks of terraform HCL.

**Comment by colinhoglund** [comment]
My mistake, I was looking off of `master`.

**Comment by apparentlymart** [comment]
Thanks for following up, @colinhoglund!

There's more information on what's going on here in [the Version Selection wiki page](https://github.com/hashicorp/hcl/wiki/Version-Selection). The short answer is that the `master` branch is going to continue to be HCL 1 for the time being in order to minimize pain for folks working with HCL 1 as a library in `GOPATH` mode, which is not able to automatically select any commit other than the latest `master` branch commit.
