### ISSUE TITLE
Sonar module?

### ISSUE THREAD

**Issue by mrPsycho** [hashicorp/hcl#314]
Is there any ways to add support of HCL to sonar? 

we are using terraform, and just thought that it would be great to have code analysis in sonar. 
but... didn't found it on sonar marketplace. 

So, is there any way to run sonar on HCL?

**Comment by apparentlymart** [comment]
Hi @mrPsycho! Sorry for the slow response.

HCL itself is just a toolkit for building languages, so I don't think it makes sense for Sonar (assuming we're talking about [SonarQube](https://www.sonarqube.org/)) to do analysis of HCL directly.

It _might_ make sense for it to analyze the Terraform language in particular, which would include both parsing the HCL syntax _and_ interpreting the Terraform-specific language constructs built on top of it. I don't have any direct experience with SonarQube, so I'm not sure what sorts of checks it normally would run, but if you have some specific ideas you could [open a feature request in the Terraform repository](https://github.com/hashicorp/terraform/issues/new?labels=enhancement&template=feature_request.md) to capture some specific things you'd find it interesting for a static analysis tool to highlight in Terraform in particular. Then perhaps Terraform could offer an interface to perform that sort of analysis which SonarQube could then potentially capture and show in its UI.

Because this seems more interesting as a Terraform feature rather than as an HCL feature, I'm going to close this out. Thanks for suggesting it, though!
