### ISSUE TITLE
hclwrite: SetAttributeValue should preserve SpacesBefore

### ISSUE THREAD

**Issue by minamijoyo** [hashicorp/hcl#316]
This issue is related to hclwrite in hcl2.

### HCL Template
```hcl
a = false
```

### Expected behavior
Updating the value of attribute `a` from `false` to `true` should preserve a space.

```hcl
a = true
```

### Actual behavior

The space is deleted.

```hcl
a =true
```

### Steps to reproduce
1. Save the following code as main.go

```go
package main

import (
	"fmt"

	"github.com/davecgh/go-spew/spew"
	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"
)

func main() {
	src := "a = false\n"
	f, _ := hclwrite.ParseConfig([]byte(src), "", hcl.Pos{Line: 1, Column: 1})
	f.Body().SetAttributeValue("a", cty.True)
	got := f.BuildTokens(nil)
	fmt.Printf("got:\n%s\n", string(got.Bytes()))
	fmt.Printf("dump:\n%s\n", spew.Sdump(got))
}
```

2. `go run main.go`

```
$ go run main.go
got:
a =true

dump:
(hclwrite.Tokens) (len=5 cap=8) {
 (*hclwrite.Token)(0xc0000d6dd0)({
  Type: (hclsyntax.TokenType) TokenIdent,
  Bytes: ([]uint8) (len=1 cap=1) {
   00000000  61                                                |a|
  },
  SpacesBefore: (int) 0
 }),
 (*hclwrite.Token)(0xc0000d6df8)({
  Type: (hclsyntax.TokenType) TokenEqual,
  Bytes: ([]uint8) (len=1 cap=1) {
   00000000  3d                                                |=|
  },
  SpacesBefore: (int) 1
 }),
 (*hclwrite.Token)(0xc00010a1b0)({
  Type: (hclsyntax.TokenType) TokenIdent,
  Bytes: ([]uint8) (len=4 cap=4) {
   00000000  74 72 75 65                                       |true|
  },
  SpacesBefore: (int) 0
 }),
 (*hclwrite.Token)(0xc0000d6e48)({
  Type: (hclsyntax.TokenType) TokenNewline,
  Bytes: ([]uint8) (len=1 cap=1) {
   00000000  0a                                                |.|
  },
  SpacesBefore: (int) 0
 }),
 (*hclwrite.Token)(0xc0000d6e70)({
  Type: (hclsyntax.TokenType) TokenEOF,
  Bytes: ([]uint8) {
  },
  SpacesBefore: (int) 0
 })
}
```

I found the test of `SetAttributeValue` compares formatted results.
https://github.com/hashicorp/hcl/blob/3c7194d96760b6b257805b615614507ca4214446/hclwrite/ast_body_test.go#L534

However, if we want to update only the value with SetAttributeValue, I think it is more natural to keep the space. Is this behavior intentional?

**Comment by apparentlymart** [comment]
Hi @minamijoyo! Thanks for reporting this.

The behavior we intended here was that translating the hclwrite AST back to a byte sequence (e.g. using `Tokens.WriteTo`) will automatically apply formatting first, and thus the other mutation methods in the package don't generally make efforts to preserve or normalize whitespace in their work.

Calling `f.BuildTokens` rather than `f.Bytes` or `f.WriteTo` bypasses that behavior, which I suppose is why the tests are recovering it by calling `format`. One way we could address this is to make `File.BuildTokens` perform the implicit `format` call, so that it would become impossible to export tokens out of the package without them being formatted first.

However, with the context I have in my mind right now I'm not sure if there would be downsides to such a thing. I'm not sure at the moment if there was a strong reason why `BuildTokens` must return the raw tokens as-is; perhaps there are some use-cases where you'd want to skip formatting altogether, but given that the mutation methods do not produce sensible spacing by default I'm skeptical. :thinking:

**Comment by minamijoyo** [comment]
@apparentlymart Thank you for your reply.
The hclwrite package makes surgical changes, so if the input is unformatted, I think we don't want to force format other than the change we intended.
But if the policy is that we can't get unformatted bytes out of the package, I'll format the output by myself for now.

**Comment by apparentlymart** [comment]
Hi @minamijoyo,

Indeed the ideal would be to make surgical changes in-place, but as `hclwrite` is currently designed the surgical update operations generally don't have access to enough context about where their changes are located in order to produce a correctly-formatted result, particuarly if the input is not already formatted correctly and it might be unclear what the "correct" formatting would be.

For that reason, we decided to simplify the problem by saying that the surgical changes are to the meaningful content of the input but do not promise to preserve the formatting. That way we avoid some hard problems like determining how much to indent parts of a multi-line expression that's being inserted if the surrounding content is inconsistently indented itself, the potential need to adjust alignment of existing attribute values when a new attribute is inserted, etc. Instead, we just force the result as a whole to be consistent with the canonical formatting, while preserving the non-whitespace content.

**Comment by minamijoyo** [comment]
@apparentlymart That make sense. I'll close this issue. Thanks!
