### ISSUE TITLE
How can I EncodeIntoBody first-class expressions?

### ISSUE THREAD

**Issue by KeisukeYamashita** [hashicorp/hcl#318]
I want to `gohcl.EncodeIntoBody(...)` use for encoding first-class expressions but I don't know how. Can somebody help me?

### Expected behavior

Generate files like 

```hcl
resource "foo" "bar" {
     for_each = var.list
     title = "huga"
}
```

### Actual behavior

With `gohcl.EncodeIntoBody(...)`, I want to create files like

```hcl
resource "foo" "bar" {
     for_each = var.list
     title = "huga"
}
```

I works with 

```golang
     f := hclwrite.NewFile()
	rootBody := f.Body()
	schema := &schema.MySchema{
		Resources: []schema.SchemaConfig{
			schema.SchemaConfig{
				Title: "hoho",
			},
		},
	}
	gohcl.EncodeIntoBody(schema, rootBody)
	err := ioutil.WriteFile("./mytest.tf", f.Bytes(), 0644)
	if err != nil {
		return err
	}

	return nil
```

But I can't find out how to do this with the first-class expression.

### Steps to reproduce
1. 
2.
3.

**Comment by apparentlymart** [comment]
Hi @KeisukeYamashita!

The `gohcl` package maps from HCL bodies to simple Go types, and so its reverse mapping back to `hclwrite` is necessarily lossy. There isn't any way to produce anything other than constant values using that API.

In order to produce a reference to another value as you showed, you need to use the lower-level API in the `hclwrite` package. [The "generateFromScratch" example](https://github.com/hashicorp/hcl/blob/3c7194d96760b6b257805b615614507ca4214446/hclwrite/examples_test.go#L11) shows how you can do that. A smaller version of that example suited to your case here might be as follows:

```go
f := hclwrite.NewEmptyFile()
rootBody := f.Body()
resourceBlock := rootBody.AppendNewBlock("resource", []string{"foo", "bar"})
resourceBody := resourceBlock.Body()
rootBody.SetAttributeTraversal("for_each", hcl.Traversal{
	hcl.TraverseRoot{Name: "var"},
	hcl.TraverseAttr{Name: "list"},
})
resourceBody.SetAttributeValue("title", cty.StringVal("huga"))

err := ioutil.WriteFile("./mytest.tf", f.Bytes(), 0644)
if err != nil {
	return err
}

return nil
```

(I just modified the other example to remove the irrelevant parts and didn't test this alone, so it might contain some minor errors.)

At the moment `hclwrite` only knows how to generate constant values and simple references as shown above. It has no API for generating more complex expressions such as function calls or arithmetic, but if you load in an existing file and modify one attribute in-place it will preserve any other expressions. That sort of "surgical" modification is the main intended use-case for `hclwrite`, though for simple cases like this it _can_ generate whole files from empty.

**Comment by KeisukeYamashita** [comment]
Hi @apparentlymart  

Thank you for your kind response. 

> At the moment hclwrite only knows how to generate constant values and simple references as shown above. 

I got it. 

I really like HCL which I think a great package.
Again, Thank you very much.
