### ISSUE TITLE
Support multiline HCL

### ISSUE THREAD

**Issue by timurb** [hashicorp/hcl#343]
I'm looking for the way to split long lines in HCL into several lines.
This is going to especially improve readability for the ternary operator.
Currently Terraform doesn't seem to support that and produces error.
Workaround is using string interpolation for that which doesn't look very good.

*Note:* this issue is NOT about using multiline strings

If this issue better suites terraform repo please let me know and I'll recreate it there.

### Failing HCL Template
```hcl
variable "input" {
  default = 1
}

resource "null_resource" "test" {
  triggers = {
    foo = var.input > 0 ?
            "foo" :
            "bar"
  }
}
```

```
$ terraform apply
Error: Invalid expression

  on test.tf line 7, in resource "null_resource" "test":
   7:
   8:

Expected the start of an expression, but found an invalid expression token.
```

### Workaround example (watch for string interpolation):
```hcl
variable "input" {
  default = 1
}

resource "null_resource" "test" {
  triggers = {
    foo = "${var.input > 0 ?
            "foo" :
            "bar"
    }"
  }
}
```

**Comment by apparentlymart** [comment]
Hi @timurb! Thank for opening this issue.

Unfortunately it looks like hashicorp/terraform#21636 made that error message unclear about what exactly the parser is complaining about, but I'm assuming where it's getting tripped up is in misunderstanding that you intended those newlines after `?` and `:` to end the argument definition, not as continuation. Because HCL's structural syntax has semantic whitespace, naked expressions split over multiple lines like you showed would be ambiguous were it supported.

To wrap an expression over multiple lines you can place it in any sort of "bracketing" construct that then serves to tell the parser the bounds for the expression. You've seen that `${` and `}` inside a template can be one such construct. The most basic bracketing construct, which carries no additional semantics whatsoever, is a pair of parentheses:

```hcl
  foo = (
    var.input > 0 ?
    "foo" :
    "bar"
  )
```

This also works for tuple constructor brackets `[ ... ]`, object constructor brackets `{ ... }`, and function calls `foo( ... )`, because all of those have an unambiguous ending marker that HCL can use to understand where the expression ends.

Does that address what you were looking for?

**Comment by timurb** [comment]
Yes, that's what I was looking for.
For some reason I didn't find anything in docs about using brackets for this task. Probably the docs are there, I just didn't spot them.
You know, when you are familiar with some language searching for certain things becomes challenging: you won't read through all the docs (because you know the topic well) and it's not so straightforward to find the right keywords for doing search.

Thanks for the quick answer! I'm closing this ticket then.
Feel free to reopen/create a new one if you need that for your improvements roadmap, etc.

**Comment by elvis2** [comment]
> Hi @timurb! Thank for opening this issue.
> 
> Unfortunately it looks like [hashicorp/terraform#21636](https://github.com/hashicorp/terraform/issues/21636) made that error message unclear about what exactly the parser is complaining about, but I'm assuming where it's getting tripped up is in misunderstanding that you intended those newlines after `?` and `:` to end the argument definition, not as continuation. Because HCL's structural syntax has semantic whitespace, naked expressions split over multiple lines like you showed would be ambiguous were it supported.
> 
> To wrap an expression over multiple lines you can place it in any sort of "bracketing" construct that then serves to tell the parser the bounds for the expression. You've seen that `${` and `}` inside a template can be one such construct. The most basic bracketing construct, which carries no additional semantics whatsoever, is a pair of parentheses:
> 
> ```terraform
>   foo = (
>     var.input > 0 ?
>     "foo" :
>     "bar"
>   )
> ```
> 
> This also works for tuple constructor brackets `[ ... ]`, object constructor brackets `{ ... }`, and function calls `foo( ... )`, because all of those have an unambiguous ending marker that HCL can use to understand where the expression ends.
> 
> Does that address what you were looking for?

Thank you for explaining this!
