### ISSUE TITLE
How to validate HCL2 syntax?

### ISSUE THREAD

**Issue by antonbabenko** [hashicorp/hcl#362]
Not exactly an issue with HCL2 but I hope to hear some answers here.

Q1: Is there a tool that can validate HCL2 syntax? I am not talking about Terraform implementation of HCL2, but pure HCL2 as according to the specification.

Q2: Are there open-source projects where HCL2 is not only read (parsing is rather easy) but also generated/updated programmatically? I didn't find any so I decided to ask HCL creators here.

Have a great day!

**Comment by apparentlymart** [comment]
Hello! Sorry I didn't see this when you originally posted it.

Our general viewpoint on HCL is that it is a library toolkit for building languages with rather than a language in its own right, and in particular "generic HCL" is really just a set of grammar rules where any meaning attributed to those arise only from an application-defined schema. In other words, HCL is a shared implementation detail of various other languages including the Terraform language, not a language in its own right.

Given that, a "generic" validator would really just be a basic syntax check, and wouldn't say anything about whether the structure is suitable for any particular situation. Given that we have to prioritize the best use of our resources, we've preferred to have applications themselves provide validators for their own languages defined in terms of the HCL grammar, because that can then take into account more interesting validation rules such as which blocks are valid in which contexts, whether arguments are of the expected types, etc.

If there is an HCL-based language whose associated application doesn't offer tools for validation and formatting, I'd suggest opening an enhancement request with that application to add such features. This library includes helpers to assist application developers in doing so, which they can then combine with application-specific logic as appropriate in order to preserve the application's intended abstraction, rather than exposing the implementation detail that the language is based on HCL grammar.

With all of that said, the generic `hclfmt` tool in this repository does end up doing a syntax check as part of its work -- because it needs to build a syntax tree in order to decide indentation -- so if you really do want to avoid using an application-specific tool then you could in principle build `hclfmt` and use it as a validator and basic formatter. That tool is there primarily as an example for application developers of how to build an application-specific formatter like `terraform fmt`, rather than being intended for routine direct use, but we aren't planning to remove it and so there's no harm in using it if you find it useful.

**Comment by crw** [comment]
Going to close this one on the assumption that @apparentlymart's answer responded fully to the original question; please let me know if there are any outstanding questions or if this should be re-opened for any other reason.
