### ISSUE TITLE
Converting an []interface{} to cty-type?

### ISSUE THREAD

**Issue by k86021** [hashicorp/hcl#364]
How can I convert an []interface{} to a cty.Type?

I am reading a set of source- and target-hcl files, into structs. And when processing the target-files I want to produce ddl-code based on the specifications in these files.

Interfaces for source and target:
```
type Source interface {
  Debug()
}

type Target interface {
  Debug()
}
```

Sources and targets are both lists of interfaces
```
sources := []Source{}
targets := []Target{}
```

and populated like this (similar for targets):
```
case "json":
	json := &Json{}
	if s.AttributesHCL != nil {
		if diag := gohcl.DecodeBody(s.AttributesHCL, evalContext, json); diag.HasErrors() {
				return []Source{}, targets, fmt.Errorf("error in decode HCL: %w", diag)
		}
	}
	sources = append(sources, json)
```

Content of Sourcefile.hcl:
```
source json "sourcesystem" {
  varchar "adr"         {path="$.path.block.adr"}
  date    "createdate"  {path="$.path.block.createdate"}
  number  "amount"      {path="$.path.block.amount"}
  number  "id"          {path="$.path.block.id"}
 }
```

The content of sources looks like this after reading sourcefile.hcl:

`&main.Json{Varchar:[]main.Varchar{main.Varchar{Name:"adr", Path:"$.path.block.adr"}}, Date:[]main.Date{main.Date{Name:"createdate", Path:"$.path.block.createdate", Format:(*string)(nil)}}, Number:[]main.Number{main.Number{Name:"amount", Path:"$.path.block.amount"}, main.Number{Name:"id", Path:"$path.block.id"}}, Boolean:[]main.Boolean(nil)}`

I'm trying to convert sources to cty-values in a func TargetEvalContext, but I'm not sure how to do this. The reason for doing this is to be able to pick the source elementes from sources based on definitions in our targetfile.hcl and process them individually before creating a DDL-output.

```
func TargetEvalContext(sources []Source) *hcl.EvalContext {

    _, source := gocty.ToCtyValue(sources, cty.Value)      <-how can sources be converted to cty into source?

    for _, s := range sources {
        log.Debugf("%# v", s)
    }

    evalContext := &hcl.EvalContext{
        Variables: map[string]cty.Value{
            "var": cty.StringVal("Dummy msg"),
        },
        Functions: map[string]function.Function{
            "upper": stdlib.UpperFunc,
        },
    }
    return evalContext
}
```
Any pointers or suggestions appreciated.

Thanks,
Bjørn M.

**Comment by azr** [comment]
Hello there, `hcldec.Decode` (from github.com/hashicorp/hcl/v2/hcldec) seems to be what you are looking for. I have recently done this for Packer: [example usage here](https://github.com/hashicorp/packer/blob/193dad46e6d15ae4ffc49a3a176c2933419ba81c/hcl2template/decode.go#L9) 

Decode takes an hcl Body and an `hcldec.Spec`, the body comes from reading the file and the Spec you will have to define; for Packer - because we have a lot of config files - I have created a code generator that does this for us but you can also manually do them. Here's an example of a working Spec:

https://github.com/hashicorp/packer/blob/840e67f7757af8e23174d709799875d9a0508699/provisioner/ansible-local/provisioner.hcl2spec.go#L43-L72

Decode will return a cty.Value that can be used in there.

**Comment by k86021** [comment]
Thank you for Your reply @azr
This is spot on for us, and as you can see described in #367 we tried this with success by creating the specs manually.

Would you by any chance have a suggestion to a solution to #367 as well?

**Comment by azr** [comment]
Yes I saw #367 and wasn't sure of the answer; I'll try to write something up. About this issue it sounds like you are sorted out so I think it's okay to close it; please reopen or comment if something's up !
