### ISSUE TITLE
Documentation for hclwrite

### ISSUE THREAD

**Issue by Ludonope** [hashicorp/hcl#373]
I am using hclwrite but I'm having an issue and I cannot find any solution anywhere.

I want to generate terraform (or more specifically terragrunt) code, but I cannot find a proper way to insert `$` symbols for interpolation.

Let's say I want to generate the following output:
```hcl
remote_state {
  config = {
    key = "${path_relative_to_include()}/terraform.tfstate"
  }
}
```

The most intuitive way would be to use the following code:
```go
f := hclwrite.NewEmptyFile()
rootBody := f.Body()

// remote_state block
stateBody := rootBody.AppendNewBlock("remote_state", nil).Body()
stateBody.SetAttributeValue("config", cty.ObjectVal(map[string]cty.Value{
	"key": cty.StringVal("${path_relative_to_include()}/terraform.tfstate"),
}))
```

However that will escape the dollar symbol and I end up with the following output:
```hcl
remote_state {
  config = {
    key = "$${path_relative_to_include()}/terraform.tfstate"
  }
}
```

For now my only solution is to put a easily identifiable prefix before it and do a string replace before writing to a file, but it's not elegant AT ALL.

Is there a way to insert an interpolation string? If so, it could be interesting to add it to the package documentation.

I also have a very similar issue with inserting a traversal directly in an object, as such:
```hcl
remote_state {
  config = {
    key = data.path.to.file
  }
}
```

In a similar fashion I'm doing some tricky stuff to get that output, but I wonder if it's natively supported.

EDIT: improved code formatting

**Comment by apparentlymart** [comment]
Hi @Ludonope,

For most use-cases involving code generation with HCL I'd recommend generating [the JSON variant](https://github.com/hashicorp/hcl/blob/hcl2/json/spec.md) instead, because that's designed to be easy for machines to generate, while the native syntax is designed to be easier for _humans_ to edit (and is, as a consequence, more work to machine-generate). I _think_ (though I'm not totally sure) that Terragrunt can support JSON syntax in a file called `terragrunt.hcl.json`. If it can, the structure to generate here would looks something like this:

```json
{
  "remote_state": {
    "config": {
      "key": "${path_relative_to_include()}/terraform.tfstate"
    }
  }
}
```

---

`hclwrite` currently has no generalized solution for producing arbitrary expressions. The `SetAttributeValue` method you saw is designed for the common case of writing a constant value into the configuration, and so it escaped the `${` sequence to make sure that the result would be interpreted as a constant string rather than as an interpolation sequence.

The best answer I have for you right now is to use the `SetAttributeRaw` method instead, and to provide the expression you want to write as a sequence of tokens:

```go
tokens := hclwrite.Tokens{
  {Type: hclsyntax.TokenOBrace, Bytes: []byte(`{`)},
  {Type: hclsyntax.TokenIdent, Bytes: []byte(`key`)},
  {Type: hclsyntax.TokenEqual, Bytes: []byte(`=`)},
  {Type: hclsyntax.TokenOQuote, Bytes: []byte(`"`)},
  {Type: hclsyntax.TokenTemplateInterp, Bytes: []byte(`${`)},
  {Type: hclsyntax.TokenIdent, Bytes: []byte(`path_relative_to_include`)},
  {Type: hclsyntax.TokenOParen, Bytes: []byte(`(`)},
  {Type: hclsyntax.TokenCParen, Bytes: []byte(`)`)},
  {Type: hclsyntax.TokenTemplateSeqEnd, Bytes: []byte(`}`)},
  {Type: hclsyntax.TokenQuotedLit, Bytes: []byte(`/terraform.tfstate`)},
  {Type: hclsyntax.TokenCQuote, Bytes: []byte(`"`)},
  {Type: hclsyntax.TokenCBrace, Bytes: []byte(`}`)},
}
stateBody.SetAttributeRaw("config", tokens)
```

A likely future addition to this API would be a `SetAttributeParseExpr` method which takes a string containing HCL native expression syntax and parses it to produce a set of tokens like the above (along with the expected syntax tree annotations) automatically, which I imagine you'd then use something like this:

```go
// NOT YET IMPLEMENTED
stateBody.SetAttributeParseExpr("config", `{key = "${path_relative_to_include()}/terraform.tfstate"}`)
```

However, the `hclwrite` functionality implemented so far has been motivated by what's been needed for other work (e.g. in Terraform or Terraform's tools). I'm not currently able to spend a lot of focused time on HCL for HCL's sake, but I'll keep this in mind as something to work on when time allows.

**Comment by Ludonope** [comment]
Thank you for that pretty complete answer!

I think a solution would be to add a `cty.RawValue` which would allow to directly inject content with no special formatting or validation. I understand why people would be against it tho.

**Comment by dgokcin** [comment]
hello @Ludonope I came up to this issue while trying to generate terragrunt files programatically. Have you figured out a better solution? I am looking for a cleaner way to do this.
