### ISSUE TITLE
RangeScanner omits trailing newline near EOF

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/hcl#378]
### HCL Template

```hcl
provider "aws" {
  access_key = "value"
}

```

with line indicies (just for clarity):

```hcl
provider "aws" {                 # 1
  access_key = "value"           # 2
}                                # 3
                                 # 4
```

### Expected behavior

I would expect the scanner to just leave interpretation of newlines up to the callback.

### Actual behavior

The `RangeScanner` doesn't pass the last (4th in the snippet above) line to the scanner callback at all.

### Context

Trailing newline may be significant for the scanner when
 - the output is used for calculating diff between formatted and unformatted configuration
 - language server needs to match position in a document to the configuration to understand what completion candidates to offer - e.g. 1st class keywords is something LS would typically want to suggest near the newline at EOF

### Steps to reproduce

```go
package main

import (
	"fmt"
	"bytes"
	"github.com/hashicorp/hcl/v2"
)

func main() {
	PrintSourceLines("test.tf", []byte(`provider "aws" {
  access_key = "value"
}
`))
}

func PrintSourceLines(filename string, s []byte) {
	if len(s) == 0 {
		return
	}

	sc := hcl.NewRangeScanner(s, filename, scanLines)
	i := 0
	for sc.Scan() {
		fmt.Printf("line %d: %q, rng: %#v\n",
			i, string(sc.Bytes()), sc.Range())
		i++
	}
}

func scanLines(data []byte, atEOF bool) (advance int, token []byte, err error) {
	if atEOF && len(data) == 0 {
		return 0, nil, nil
	}
	if i := bytes.IndexByte(data, '\n'); i >= 0 {
		// We have a full newline-terminated line.
		return i + 1, data[0 : i+1], nil
	}
	// If we're at EOF, we have a final, non-terminated line. Return it.
	if atEOF {
		return len(data), data, nil
	}
	// Request more data.
	return 0, nil, nil
}
```
```
line 0: "provider \"aws\" {\n", rng: hcl.Range{Filename:"test.tf", Start:hcl.Pos{Line:1, Column:1, Byte:0}, End:hcl.Pos{Line:2, Column:1, Byte:17}}
line 1: "  access_key = \"value\"\n", rng: hcl.Range{Filename:"test.tf", Start:hcl.Pos{Line:2, Column:1, Byte:17}, End:hcl.Pos{Line:3, Column:1, Byte:40}}
line 2: "}\n", rng: hcl.Range{Filename:"test.tf", Start:hcl.Pos{Line:3, Column:1, Byte:40}, End:hcl.Pos{Line:4, Column:1, Byte:42}}
```

**Comment by apparentlymart** [comment]
I think this is a subtle interaction between your `scanLines` function and the following logic in the `Scan` method:

https://github.com/hashicorp/hcl/blob/50eda8bd0cd6b93b678d287783219a89e15e9d4b/pos_scanner.go#L71-L73

Your split function starts with the following condition:

```go
	if atEOF && len(data) == 0 {
		return 0, nil, nil
	}
```

Returning `0, nil, nil` when `atEOF` is set is the termination condition for scanning, so the `for sc.Scan()` loop would terminate without processing that final result. The input in your example seems to only have one newline after the closing brace, so that "final line" you can see in your editor is, in a sense, a "virtual" line only.

With that said, my intent for `RangeScanner` was to produce the same sequence of slices as [`bufio.Scanner`](https://godoc.org/bufio#Scanner), so I'd be interested to see whether that implementation behaves in the same way as `hcl.RangeScanner` or if it produces that extra "virtual line" you're looking for. If `bufio.Scanner` does it then I'd consider it a bug in `hcl.RangeScanner` that its behavior is different in this case.

If `bufio.Scanner` agrees that this extra "virtual line" doesn't really exist, maybe you could "fake" it for your use-case in particular by always introducing an artificial additional `\n` at the end of the input, which I think should ensure that the last line you read in always ends at the _user-perceived_ end of the file (which I'm considering as the greatest position in the editor buffer where the cursor could be placed). :thinking:

**Comment by radeksimko** [comment]
> The input in your example seems to only have one newline after the closing brace, so that "final line" you can see in your editor is, in a sense, a "virtual" line only.

Oh, that is a very good point! 🤔 I did not realize that before.

> I'd be interested to see whether that implementation behaves in the same way as hcl.RangeScanner or if it produces that extra "virtual line" you're looking for

I will check and report back.

**Comment by radeksimko** [comment]
Confirmed the implementation is aligned with `bufio.Scanner` behaviour: https://play.golang.org/p/fU5-ctGDpQ8

**Comment by radeksimko** [comment]
Also just for completeness here's the commit implementing a solution very similar to what you described:
https://github.com/hashicorp/terraform-ls/pull/104/commits/a397452791de55206d8a350e363ef0dfd82c55c5

Thank you for spotting the difference between "virtual" and real line 🙏
