### ISSUE TITLE
Missing definition for type string in HCL Syntax specification for Lexical Elements

### ISSUE THREAD

**Issue by tycarac** [hashicorp/hcl#391]
### HCL Template
The HCL spec is missing a definition for type string in [Lexical Elements](https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/spec.md#lexical-elements)

### Expected behavior
Add short explanation for:
1. Use of quotes (single quote, double quote, grave accent)
2. Accepted escape sequences
3. Character encoding

I am not asking for character mappings to unicode as it would overly and needlessly complicate the specification.

### Actual behavior
I used single quotes for strings and it crashed Terraform application.  On submitting a crash report, I was advised not to use single quotes.  I could not find what was accepted in the HCL Syntax specification.

### References
Terraform issue #25366 [0.13.0-beta2 crash report](https://github.com/hashicorp/terraform/issues/25366)

**Comment by apparentlymart** [comment]
Hi @tycarac,

I think the information you are looking for is in the section [Template Expressions](https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/spec.md#template-expressions), aside from the character encoding which is defined as UTF-8 in [Source Code Representation](https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/spec.md#source-code-representation). HCL has no standalone "string literal" construct to describe in "lexical elements"; string literals only exist as part of template expressions.

Since your original issue was over in Terraform, you might also be interested to refer to Terraform's documentation on [String Literals](https://www.terraform.io/docs/configuration/expressions.html#string-literals) and [String Templates](https://www.terraform.io/docs/configuration/expressions.html#string-templates), which are written to be end-user documentation rather than as guidance for a parser implementer (as is the case for the HCL native syntax specification).

If you'd like to know anything else that isn't covered in one of those sources, please let me know! Thanks.

**Comment by tycarac** [comment]
@apparentlymart 
Thanks for your response.  I have been looking at the references you provided and I have what I need for now.

As part of my learning of Terraform, I have been putting together an ANTLR lexer/parser template for Terraform.  I am doing so as I have not played with grammar tools before and I am finding it building a deeper understanding of the Terraform language.  And for the fun-of-it.

Though I have a small idea how I might use ANTLR parser, I am finding the complexity of the parser grammar rules reflects the complexity and edge cases of the language.  Parsing the [AWS VPC Terraform module](https://github.com/terraform-aws-modules/terraform-aws-vpc), the most example complex I have found so far, has been challenging.


So are the grammars used in the HCL specification from a grammar formal language and taken from combined grammar?  If so, is there a web link to it?

**Comment by apparentlymart** [comment]
The second generation of HCL (which Terraform uses) has a lexer generated from [a Ragel grammar](https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/scan_tokens.rl), but the parsing portion is [a hand-written recursive descent parser](https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/parser.go) using the tokens from the generated scanner.

The scanner itself is a little unusual in that it switches between a number of different modes during its work: config, expression, and string templates. It achieves that by using Ragel's ability to manipulate a mode stack from inside the grammar actions, so it can remember that e.g. it's currently in a template inside an expression inside a template inside an expression inside a config, popping out of those modes when it encounters their closing delimiters. I'm not familiar with ANTLR so I'm not sure if it has an equivalent, but [`pushMode` and `popMode`](https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md#mode-pushmode-popmode-and-more) look promising at first look.

Aside from that unusual characteristic of the scanner, I think it should be possible to translate the recursive-descent parser code into an ANTLR grammar if you like, though it will probably be a bit arduous to read through the imperative-style Go code (with state transition decisions expressed using `switch` and `if` statements) and figure out how to translate it into declarative-style grammar. The hand-written parser has some error-recovery heuristics in it which add some complexity, but in your implementation you could choose to ignore those and just halt parsing if you encounter an invalid production.
