### ISSUE TITLE
RFC: HCL schema

### ISSUE THREAD

**Issue by alecthomas** [hashicorp/hcl#409]
Hi,

We at CashApp love HCL and use it extensively. We have our own [HCL library](https://github.com/alecthomas/hcl) for various reasons, and have also implemented rudimentary [schema support](https://github.com/alecthomas/hcl#schema-reflection). We're planning on extending the schema and writing a general purpose [LSP](https://microsoft.github.io/language-server-protocol/) server that uses this schema to automatically provide intellisense, completion, etc.

We would like to keep the schema relatively straightforward rather than encumber it with complexity a la JSON schema. This somewhat limits what the schema can represent, but this tradeoff is acceptable to us. As an example of what we are considering, enum and default values might be represented as something like this:

```hcl
kind = type(string, enum("s3", "dynamodb"), default("s3"))
```

At this point it seems responsible to see if Hashicorp has any interest in collaborating on a schema!

All the best,
Alec

**Comment by alecthomas** [comment]
I forgot to say that if there's already some kind of schema that I'm not aware of, please let me know!

**Comment by radeksimko** [comment]
Hi @alecthomas 
For context I work at HashiCorp and my main current focus is the recently created [Terraform Language Server](https://github.com/hashicorp/terraform-ls).

That language server currently has its own "decoder" which turns parsed `hcl` or `hclsyntax` types into some more meaningful types based on the plugin schema. That is a form of [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) decoder which we shipped some time ago and I then started working on more generic HCL decoder which could serve any language server, including the Terraform one, but also a "general purpose" one.

With that in mind I'd be more than happy to collaborate with you on this.

I'd certainly want to see a generic HCL language server, but I'm unsure what capabilities such server can provide. We went through a few iterations of a proposal for the general purpose decoder internally, which also includes LSP-friendly schema representation. It looks like we _might_ be able to provide static, machine-readable schema. This means that such generic LS could potentially read such static schema and provide functionality based on that.

I'd be happy to share the progress, but given the amount of content and needed context it's perhaps better to do that initially outside of GitHub - feel free to ping me on radek`<at>`hashicorp.com if you're interested in a chat and/or reading an RFC and providing feedback.

With all that said I'm not sure we can provide a lot of functionality in a generic language server without schema.
The only capabilities coming to my mind are:
 - formatting
 - syntax highlighting (when that is actually introduced into LSP)
 - some form of symbols
 - diagnostics

There is a lot more value that product-specific language server can offer though - e.g. reflecting the fact that schemas change between versions and be able to detect the appropriate version and schema.

> We have our own HCL library for various reasons, and have also implemented rudimentary schema support. 

I looked briefly at your library and there's a few things I should probably mention

 - it seems to be focused on HCL1. While there are still products that use HCL1 (Vault, Consul), other HashiCorp products have already migrated (Terraform, Packer) or plan to migrate (Nomad) to HCL2. All of our language server related work (implicitly) basically excludes HCL1.
 - one of the differences between HCL1 and HCL2 is that HCL2 integrates with a type system - https://github.com/zclconf/go-cty which also supports complex variable types, like objects or maps
 - relatedly HCL2 has [`typeexpr` package](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.6.0/ext/typeexpr) which provides Terraform decoding of type definitions for variables that you mentioned in your Readme

There is a number of schema packages/libraries in active use today

   - [`hcl.BlockHeaderSchema`](https://pkg.go.dev/github.com/hashicorp/hcl/v2#BlockHeaderSchema), [`hcl.BodySchema`](https://pkg.go.dev/github.com/hashicorp/hcl/v2#BodySchema) and [`hcl.AttributeSchema`](https://pkg.go.dev/github.com/hashicorp/hcl/v2#AttributeSchema) (in use e.g. by Terraform core)
   - [hcldec](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.6.0/hcldec) library - which is probably the simplest of all, basically turns config into a nested `cty.Value` (in use by Packer 1.5+)
   - [Terraform plugin SDK helper/schema](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.4/helper/schema) (in use by all Terraform plugins)
   - [Terraform core's `configschema` package](https://pkg.go.dev/github.com/hashicorp/terraform@v0.13.4/configs/configschema) - mostly representation of the above plugin schema on core's side
   - [Nomad's hclspec](https://pkg.go.dev/github.com/hashicorp/nomad/plugins/shared/hclspec)
   - [gohcl](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.6.0/gohcl) allows mapping to structs directly - very similar to https://github.com/alecthomas/hcl#struct-field-tags (v1 version effectively used by Vault and Consul, v2 used by some products we plan to announce [this week](https://digital.hashiconf.com/schedule/day-3) 😉  )

Each has a slightly different purpose and also different tradeoffs. None of them are however _designed_ to provide metadata to a language server. Beyond LSP support I'd be curious to see if you have a use case that isn't covered by any of them?

**Comment by alecthomas** [comment]
> For context I work at HashiCorp and my main current focus is the recently created Terraform Language Server.

Nice!

I think there was some misunderstanding. I was suggesting a HCL schema _in HCL_ not in Go, CTY, or anything separate. _Basically, the equivalent of JSON schema, for HCL._

The idea would then be that the LSP would understand the structure and (to a limited extent) the semantics of _any_ HCL file, not just TF.

> With all that said I'm not sure we can provide a lot of functionality in a generic language server **without schema**.

Exactly! Which is why I'm suggesting a schema that is reusable across many different HCL backends, not just TF.

> it seems to be focused on HCL1.

Yes, that is correct. HCL2 and the hcl2 library are much more complex than we require (or desire), which is one of the motivations for our library.

> There is a number of schema packages/libraries in active use today

Yep, I'm aware of most of these (except Nomad's hclspec, which is new to me). In fact, all of these various partial schemas illustrate my point even further. A single schema specification would unify all of these, and allow non-Hashicorp users to write their own schema's easily, generalise validation, _and_ allow a generic LSP.

> gohcl allows mapping to structs directly - very similar to https://github.com/alecthomas/hcl#struct-field-tags (v1 version effectively used by Vault and Consul, v2 used by some products we plan to announce this week 😉 )

Yes, our HCL library is intentionally tag-compatible with gohcl.

Anyway, hopefully that clarifies what I'm suggesting: **HCL Schema would be to HCL what JSON Schema is to JSON.**

**Comment by alecthomas** [comment]
I forgot to mention, a secondary goal of the schema is so that it can be used automatically as documentation for users.

**Comment by radeksimko** [comment]
> Yes, that is correct. HCL2 and the hcl2 library are much more complex than we require (or desire), which is one of the motivations for our library.

I may be completely biased, given how much time I have spent working on Terraform and reading through HCL's codebase, but the way I see it is that much of the complexity is somewhat necessary to serve all the different tools which have complex configuration formats/schemas.

Either way HashiCorp's current position is that HCL1 is no longer maintained and will not see any significant changes, including a schema model, so if HCL1 is for some reason a hard requirement for you, we are unfortunately unlikely to be able to collaborate or help each other.

> Which is why I'm suggesting a schema that is reusable across many different HCL backends, not just TF.
>  In fact, all of these various partial schemas illustrate my point even further. A single schema specification would unify all of these, and allow non-Hashicorp users to write their own schema's easily, generalise validation, and allow a generic LSP.

I acknowledge the diversity of schema implementations may be annoying from some perspectives and I agree it would be great if all tools used the same schema. However I also see the history and use cases behind most of these schemas. They were not created because someone was unaware of the other schemas. They exist to solve different problems and make different trade-offs based on the context and needs of each tool and I expect many of them will continue to exist in the foreseeable future.

With that in mind I trust you also have a reason for a simpler or any other schema to exist - I wasn't in any way challenging the existence of it! 😄  I was rather curious about the particular use cases it solves, because I believe that context/perspective is always important and many HashiCorp tools likely have slightly different needs and require different levels of complexity.

If I was to break down the complex process from the beginning to the end, it would look like this:

1. raw bytes
2. HCL tokens (e.g. string literal, quote, brace, equal sign, ...)
3. parsed HCL types (e.g. blocks, bodies, attributes)
4. meaningful structures (e.g. resources or providers in Terraform)

The first 3 stages are more or less same across all HashiCorp (HCL2 at least) tools from what I can tell, despite the fact that they apply different schemas, or even combination of different schemas between 3 and 4.

The LSP-compatible schema I'm working on will also be technically _another_ schema implementation, but we still intend to reuse all the tokenization and parsing logic of HCL2 in the language server.

It's possible that we will look into bringing feature parity between some these schemas as we integrate them with LSP - e.g. most of them don't have a "description" field and it's possible that some of these schemas become redundant at some point, but I'm really just guessing at this point.

From a pragmatic perspective I see this as a long journey and having different schemas - even if temporarily - is a necessary part of that journey. We can't just create a new schema in a void and expect all teams/tools to start using it, I think we have to fully understand their needs and understand if we can serve these needs and how. Then when/if we are ready to serve them we need to provide some migration paths for both developers and end users.

> a secondary goal of the schema is so that it can be used automatically as documentation for users.

That is also a goal for the schema I'm working on.

--- 

I think the best way forward may be exploring HCL2 and implementing your schema on top of that parser, like most of the other schemas are implemented, then a conversion function can be created and we can all use the same language server or at the very least share some libraries, despite different schema implementations.

**Comment by alecthomas** [comment]
> a secondary goal of the schema is so that it can be used automatically as documentation for users.

I did forget another goal - extending HCL's usefulness outside of the Go ecosystem. Without a non-Go schema, HCL's reach is limited.

> Either way HashiCorp's current position is that HCL1 is no longer maintained and will not see any significant changes, including a schema model, so if HCL1 is for some reason a hard requirement for you, we are unfortunately unlikely to be able to collaborate or help each other.

The language itself is not a hard requirement, in fact we'll likely have to extend the library to implement it if we support HCL based schemas in a more generic way.

> I acknowledge the diversity of schema implementations may be annoying from some perspectives and I agree it would be great if all tools used the same schema. However I also see the history and use cases behind most of these schemas. They were not created because someone was unaware of the other schemas. They exist to solve different problems and make different trade-offs based on the context and needs of each tool and I expect many of them will continue to exist in the foreseeable future.

I'm a bit confused as there's no direct response to whether there's interest in HCL schemas, but to summarise I think you acknowledge that there are a lot of schemas, you're writing a new one (in Go I presume), but there's no interest in writing a HCL based schema or consolidating or collaborating in any way?

> From a pragmatic perspective I see this as a long journey and having different schemas - even if temporarily - is a necessary part of that journey. We can't just create a new schema in a void and expect all teams/tools to start using it, I think we have to fully understand their needs and understand if we can serve these needs and how. Then when/if we are ready to serve them we need to provide some migration paths for both developers and end users.

Yes, I don't think there was any suggestion that there would be an immediate solution, ever. This was to get the ball rolling so to speak.

Anyway, as it sounds like there's no interest, which is a totally reasonable response!

All the best,
Alec

**Comment by radeksimko** [comment]
> I did forget another goal - extending HCL's usefulness outside of the Go ecosystem. Without a non-Go schema, HCL's reach is limited.

I am personally not aware of any plans within HashiCorp for a non-Go implementation of a HCL parser, but I am aware of at least one alternative implementation in Java/Kotlin. If you want to go down that route, I would then highly recommend reviewing Ragel definitions in the hclsyntax package: https://github.com/hashicorp/hcl/tree/hcl2/hclsyntax (*.rl), so that you don't reimplement everything from scratch and retain the same behaviours at least for the tokenizer.

> I'm a bit confused as there's no direct response to whether there's interest in HCL schemas, but to summarise I think you acknowledge that there are a lot of schemas, you're writing a new one (in Go I presume), but there's no interest in writing a HCL based schema or consolidating or collaborating in any way?

Sorry for the confusion.

There is certainly interest in new schemas on top of HCL2. You will however get the best UX and support if you implement it the way I described - i.e. if you don't try to reimplement the tokenization or parsing and leverage the existing logic for these operations in the existing Go HCL2 library. Then I think we can retain some compatibility between all the different schemas and convert between each other.

This is obviously assuming that schemas are _convertible_ in some way, which I guess also assumes that the schema eventually reaches a point where it's represented as some Go types, which is likely to be the case even if it's initially declared as "bytes in a file" which _itself_ is HCL config, but technically there are ways of converting schemas between languages, if we really wanted to (e.g. it can be de/serialized in JSON).

### Example

`hcl.AttrSpec` is convertible to `hcl.AttributeSchema` roughly like this:

```go
fromSchema := hcldec.AttrSpec{
  Name: "region",
  Type: cty.String,
  Required: true,
}
toSchema := hcl.AttributeSchema{
    Name: fromSchema.Name,
    Required: fromSchema.Required,
}
```
Here we lose `Type`, but that's acceptable if the conversion was done for a tool which accepts the target schema format as it probably doesn't care about the type anyway.
Similar examples can be modelled for other parts (blocks, bodies) of most other schemas in both directions.

I hope this helps clear out some of the confusion.
