### ISSUE TITLE
Please document how to install the cli tools

### ISSUE THREAD

**Issue by Ramblurr** [hashicorp/hcl#500]
I see that in [cmd/](https://github.com/hashicorp/hcl/tree/main/cmd) there is an `hclfmt` tool.

How can I install this tool to format my hcl2 files (specifically, nomad job specs)? Are there pre built binaries available? I couldn't find any at https://releases.hashicorp.com/

**Comment by apparentlymart** [comment]
Hi @Ramblurr,

The applications that use HCL typically include a formatting command of their own which understands each application's specific conventions. While you could in principle use the generic `hclfmt` to achieve some basic formatting of your Nomad job specifications, it might also be worth discussing with the Nomad team the possibility of it offering a command like `nomad fmt` so that you don't need to install anything extra to achieve that. (This matches with `terraform fmt` and `packer fmt`, but perhaps the Nomad team will have a reason to choose a different convention.)

In the meantime though, if you wish to use `hclfmt` then you'll need to build it yourself from source code, because we maintain this repository primarily as a library and don't publish the ancillary tools as products in their own right. (They exist mainly as examples for applications to build from.)

**Comment by nahsi** [comment]
@Ramblurr you can install hclfmt using `go install`
```
go install github.com/hashicorp/hcl/v2/cmd/hclfmt@latest
```
Here is a proposal tNomad team: https://github.com/hashicorp/nomad/issues/11757
