### ISSUE TITLE
How to ommitempty attributes?

### ISSUE THREAD

**Issue by amanenk** [hashicorp/hcl#501]
Hello. I am trying to make my program generate a config. I don't want empty items to be generated in the final file. Is there a tag to tell encoder to skip optional values?
here is my code:
```
  package main

  import (
    "fmt"

    "github.com/hashicorp/hcl/v2/gohcl"
    "github.com/hashicorp/hcl/v2/hclwrite"
  )

  type Test struct {
    X string `hcl:"x"`
    Y string `hcl:"y,optional"`
    Z string `hcl:"z,optional"`
  }

  func main() {
    t := Test{
      Y: "1",
    }
    f := hclwrite.NewEmptyFile()
    gohcl.EncodeIntoBody(t, f.Body())

    fmt.Println(string(f.Bytes()))
  }
```
the result is:
```
x = "2"
y = "1"
z = ""
```
I want to have next output:
```
x = "2"
y = "1"
```
Is there a way to do it?

**Comment by apparentlymart** [comment]
Hi @amanenk,

The original model in `gohcl` was for optional attributes to always be represented by pointer types so that `nil` could unambiguously represent the "unset" state. We later accepted this `,optional` modifier in response to a request to support _decoding_ optional attributes into the zero value, at the expense of some ambiguity, but the design for that didn't include any modifications to the config _generation_ logic and so I think there's an asymmetry here where this approach won't work for what you are trying to do.

Instead, I think you'll need to follow the original `gohcl` design here and make `Y` and `Z` both be `*string` attributes rather than just `string`, which will automatically make `gohcl` treat them as optional. When you `EncodeIntoBody` from a struct like that, it should automatically skip any fields set to `nil`, achieving the output you showed here if `Z` were left as `nil`, for example.

**Comment by amanenk** [comment]
Thank you for such a clear explanation. It works for me.
