### ISSUE TITLE
HCL Parser errors on multiple conditions

### ISSUE THREAD

**Issue by KetchupBomb** [hashicorp/hcl#509]
Hello hashicorp/hcl,

When using [the Go package `github.com/hashicorp/hcl/v2`](https://pkg.go.dev/github.com/hashicorp/hcl/v2), it fails to parse a source file which has a `data` block containing 2 `condition` attributes:

```terraform
data "aws_iam_policy_document" "foo" {
  statement {
    ...  // Omitted
    condition = {
      test     = "ForAnyValue:StringNotLike"
      variable = "aws:TagKeys"
      values = [
        "bar",
      ]
    }

    condition = {
      test     = "StringEquals"
      variable = "aws:RequestedRegion"
      values = [
        "bz",
      ]
    }
  }
}
```

```
2022/01/21 13:53:01 failed to parse config example.tf: example.tf: Attribute redefined; The argument "condition" was already set at example.tf. Each argument may be set only once.
```

According to [the documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document), multiple `condition`s seem to be a valid use case:

> When using multiple `condition` blocks, they must _all_ evaluate to true for the policy statement to apply. In other words, AWS evaluates the conditions as though with an "AND" boolean operation.

---

Seems like the relevant code section is in the parser:

https://github.com/hashicorp/hcl/blob/81b680d1562e4ee83af40a3917d13659bb455a8d/hclsyntax/parser.go#L51-L64

---

Is this correct behavior? It doesn't seem like it.

**Comment by apparentlymart** [comment]
Hi @KetchupBomb!

According to the documentation you linked, I think the expected syntax for what you were trying here would be the following, where each statement is a nested object declared using a block, rather than as a value assigned to an attribute of the parent object:

```hcl
data "aws_iam_policy_document" "foo" {
  statement {
    ...  // Omitted
    condition {
      test     = "ForAnyValue:StringNotLike"
      variable = "aws:TagKeys"
      values = [
        "bar",
      ]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:RequestedRegion"
      values = [
        "bz",
      ]
    }
  }
}
```

This distinction is a subtle one when an attribute is declared as accepting a map or object type, but in the realm of Terraform providers you can typically recognize the distinction by the name: this is a singular noun for something that can be declared multiple times, which typically means we're talking about multiple nested objects declared as blocks. It's unfortunate that provider documentation doesn't always make that clear, but the example on that documentation page at least seems to confirm my theory here.

---

For HCL's part, one unfortunate thing here is that your example has errors at two levels of abstraction:

1. From an HCL syntax perspective, it's invalid to declare the same argument multiple times.
2. From Terraform and this provider's perspective, it's invalid to declare `statement` as an argument rather than a nested block.

Unfortunately, because HCL's parser "goes first" the error message for (1) masks the error message for (2). Based on my knowledge of Terraform, I expect that if you were to change your example to only have _one_ `condition` argument but to keep using the `condition = { ... }` argument syntax then you'd then see the error for problem 2 above, which would say something like "An argument named `statement` is not expected here. Did you mean to declare a block of type `statement`?".

I would prefer to be able to invert this so that the more-context-rich Terraform-level message could shine through here, but I can't see any straightforward way to achieve that given that HCL's parsing and analysis must always happen first in order to create the higher-level data structures that Terraform then works with. :thinking:

**Comment by KetchupBomb** [comment]
Ah, I see. Thank you for the clear explanation and cooperative nudge to help me see the difference between object blocks and attributes.

I also see how/why the HCL parser may not be able to more accurately report what's "wrong" with how we have code. I'll leave that for others to debate if desired.

Closing for now. Thanks again, @apparentlymart!
