### ISSUE TITLE
inline block  support like yaml

### ISSUE THREAD

**Issue by calvin2021y** [hashicorp/hcl#528]
When build a huge file with HCL, the line number will add into ten  thousand lines without inline block syntax.

Add this fix the problem:

```hcl
job check1 {root="/tmp", script="test.py"}
```

**Comment by apparentlymart** [comment]
Hi @calvin2021y,

Requiring a separate line for each argument was an intentional design decision to keep typical configuration files "scannable" vertically. As a pragmatic compromise we do allow a single-line syntax for when there is only one argument inside, but as you have seen that doesn't generalize to arbitrary numbers of nested arguments.

It sounds like the language you are designing might be of a scale outside the design goals of HCL. If YAML is a better fit for your particular use case then I would suggest there's no harm in using it! These different building blocks have differing design goals.
