### ISSUE TITLE
hclwrite parser fails to parse quoted numeric identifiers

### ISSUE THREAD

**Issue by ssoriche** [hashicorp/hcl#541]
I have a project where we have local variables for aws account IDs (which are all numeric), the specification states that numeric identifiers must be quoted, but hclwrite parser fails to parse them (Terraform at least 0.11.15 works with them).

The definition looks like this:

```
locals {
  sibling_tier_account_id {
    "123456789012" = "987654321098"
  }
}
```

I've created a test that fails with the following:

```
❮ go test ./hclwrite/...
--- FAIL: TestParse (0.00s)
    --- FAIL: TestParse/"1"_=_foo[bar].baz_ (0.00s)
        parser_test.go:1283:  - :1,1-2: Invalid argument name; Argument names must not be quoted.
        parser_test.go:1285: unexpected diagnostics
FAIL
FAIL    github.com/hashicorp/hcl/v2/hclwrite    0.318s
ok      github.com/hashicorp/hcl/v2/hclwrite/fuzz       (cached)
FAIL
```

While I have a failing test, I'm not sure of how/where to fix this myself, so opened an issue.

**Comment by apparentlymart** [comment]
Hi @ssoriche!

I think what you've encountered here is an intentional difference between the syntax for an argument inside a body and the syntax for an object constructor expression.

Arguments inside a body (which includes arguments inside a nested block) are required by the parser to be valid identifiers, so there is no syntax for writing an argument name that isn't a valid identifier.

However, what you have here seems to want to be an expression producing an object-typed value or a map-typed value, which would take a different syntax to present it as an argument whose value happens to be an object constructor:

```hcl
locals {
  sibling_tier_account_id = {
    "123456789012" = "987654321098"
  }
}
```

The extra `=` after `sibling_tier_account_id` tells the parser that `sibling_tier_account_id` is intended to be an argument inside the locals block rather than a nested block with its own arguments inside, and so the right-hand-side of the equals sign can be any arbitrary expression syntax, which includes object constructor syntax like the above but also includes references to variables and calls to functions:

```hcl
locals {
  sibling_tier_account_id = a # if "a" is of a suitable type
}
```

```hcl
locals {
  sibling_tier_account_id = merge(a, b) # if "merge" is a function that returns a suitable type
}
```

Terraform v0.11 and earlier do not use HCL 2 and so indeed there are various inputs that Terraform v0.11 will accept that modern HCL will not, and conversely various inputs that modern HCL will accept that Terraform v0.11 would not. If you want to manipulate configuration files written in the old Terraform language from Terraform v0.11 and earlier, you will need to use the v1.x series of HCL, which has a different API and a parser which can get away with allowing a lot more ambiguity due to HCL v1 being a considerably smaller language.

Your original example would not be accepted by modern Terraform, for the same reason that `hclwrite` will not accept it. However, the rewritten version I showed above with `sibling_tier_account_id` given as an argument inside the `locals` block rather than as a nested block should work with modern Terraform and with `hclwrite`.

Given that, this all seems to be working as intended to me. I think the root cause is that you are trying to parse an obsolete version of the Terraform language with the modern parser, and so to move forward you will either need to use the modern Terraform language or use the legacy parser.

**Comment by ssoriche** [comment]
Thank you for the thorough explanation!

We're trying to use terratag to tag our AWS resources, and as I was reading through their documentation came to the understanding that the parser they use would parse both hcl1 and hcl2, which it is doing, except for this one instance. 

I then dug through their code to find that it was hclwriter that was being used to parse, and made the leap that it should be able to parse this. I understand why it doesn't, and why it is not intended to now.

Again, thank you for taking the time to explain.
