### ISSUE TITLE
hclwrite ListVal does not write every entry in a new line

### ISSUE THREAD

**Issue by Junkern** [hashicorp/hcl#542]
When using
```
list := cty.ListVal(listOfHashes)
barBody.SetAttributeValue("hashes", list)
```
the resulting HCL file does not have a newline for every list entry. Is it possible to somehow.e.g  add a flag `newlineForEveryEntry` so that every list entry gets written into a new line?

_Context_: I am programmatically adding hashes to the `.terraform.lock.hcl` file. In order to do that I am using this repository to parse the lockfile, add some hashes to every entry and then also to write back the new data.

The lockfile created by `terraform int` does have one line per hash. The hcl file created by `hclwrite` does not, this leads to many changes in the lockfile. The formatting can be corrected by running `terraform init` again, but that sounds more like a workaround :D

**Comment by apparentlymart** [comment]
According to the Terraform codebase, it is intentionally implementing its own tokenization if that argument so that future changes here would not change what `terraform init` generates:
https://github.com/hashicorp/terraform/blob/aeefde7428b836646ba9622f1bb313e6dfe2ca87/internal/depsfile/locks_file.go#L454

Making hclwrite generate more readable list serialization is of course a reasonable request independently of that, but I'm pointing this out because if your goal is to be consistent with what Terraform is doing then it might be best to follow the strategy Terraform itself is following and thus lock in to the format Terraform is intentionally trying to preserve, even if this library were to drift away from what `terraform init` does in the future (and thereby potentially break your program again).

Note that this part of `hclwrite` is intentionally a "good enough" way to get an effect similar to e.g. typical JSON encoding where you don't really care exactly how it is formatted and primarily just care about it being a valid serialization of the input. That means that I would expect to close this issue by changing the default behavior, rather than by adding an API for detailed customization via options. Constructing tokens directly is the answer for a caller than needs exacting control over what exactly is generated, just as Terraform is doing here.

**Comment by Junkern** [comment]
Thank you for the explanation and the link, this helps a lot :)
Will then use the path us constructing tokens directly.
