### ISSUE TITLE
Decode returning errors upon decoding policy referring resources not present

### ISSUE THREAD

**Issue by cxMiguelSilva** [hashicorp/hcl#544]
When using the Decode function present in hcldec package, errors are returned once a body with missing targeted resources is passed. The error returned are classified as "Unknown variable".  
Is this the expected behavior? If so is there any workaround to ignore/bypass those missing resources?

**Comment by apparentlymart** [comment]
Hi @cxMiguelSilva!

You are using the word "resources", which isn't really an HCL term and so I suspect you're trying to do something with Terraform. It would help if you can describe what you are trying to do _in HCL terms_, rather than in Terraform's terms, so that we can answer it from an HCL perspective.

Alternatively, if you'd rather focus on how to solve what you are trying to solve with Terraform itself, we could talk about it in [Terraform's community forum](https://discuss.hashicorp.com/c/terraform-core/27).

**Comment by cxMiguelSilva** [comment]
I created this thread here because the package in use is imported from `github.com/hashicorp/hcl/v2/hcldec`. Sorry if it is misplaced.
In the call of the function `hcldec.Decode()` is passed a variable of type `hcl.Body` in it is present the blocks parsed from Terraform file of the type statement. If it is given a variable that targets a block not present in the body a error is returned with the summary as  "Unknown Variable". 
Is this the expected behavior? If so is there any workaround to ignore/bypass those missing targeted blocks?
