### ISSUE TITLE
Help decoding Terraform required_providers

### ISSUE THREAD

**Issue by matt-FFFFFF** [hashicorp/hcl#545]
Hi,

I'm having trouble coming up with a Go struct model to decode the terraform required_providers block into.

I'm confused how to represent the fields for the `required_providers`. They are not fixed values so I don't know how to design the structs to fit this model.

Any help appreciated!

For reference, the Terraform:

```terraform
terraform {
  required_providers {
    azapi = {
      source  = "azure/azapi"
      version = ">= 0.3.0"
    }
    azurerm = {
      source  = "hasicorp/azurerm"
      version = ">= 3.7.0"
    }
  }
}

```

This is what I've come up with...

```go
type TerraformTF struct {
	Terraform *TerraformTFBlock `hcl:"terraform,block"`
}

type TerraformTFBlock struct {
	TerraformTFRequiredProviders *TerraformTFRequiredProviders `hcl:"required_providers,block"`
}

type TerraformTFRequiredProviders struct {
	//???
}

type TerraformTFRequiredProvider struct {
	Source  string `hcl:"source"`
	Version string `hcl:"version"`
}
```

**Comment by apparentlymart** [comment]
Hi @matt-FFFFFF!

I think the best plan here would be to review [Terraform's own code for decoding this block](https://github.com/hashicorp/terraform/blob/ad5ac89461b15095a23b5921433ffd77b3b85d17/internal/configs/provider_requirements.go#L30), and do what it's doing.

`gohcl` only supports a subset of HCL, so it might not be possible to fully implement this using that wrapper package. Terraform does not use `gohcl` and uses the lowest-level HCL API instead. It may be possible to implement _parts_ of this problem using `gohcl`, but I expect it's probably easiest to just copy Terraform's implementation as a starting point and reduce it down to the subset you need.

**Comment by matt-FFFFFF** [comment]
Thanks @apparentlymart - will check it out :)

**Comment by apparentlymart** [comment]
Another option that didn't occur to me yesterday, since I was approaching this from an HCL mindset rather than a Terraform one, is that the Terraform team maintains a separate library [terraform-config-inspect](https://pkg.go.dev/github.com/hashicorp/terraform-config-inspect/tfconfig) which knows how to decode a subset of the Terraform language (focused on declarations and dependencies, for tooling purposes) which includes the provider requirements. You can find the results of decoding the `required_providers` block in `Module.RequiredProviders` after successfully decoding a module.

**Comment by matt-FFFFFF** [comment]
Another great suggestion - thanks!

**Comment by apparentlymart** [comment]
Hi @AlexFromXD,

Since that is more of a Terraform question than an HCL question, I suggest starting a topic in [Terraform's community forum](https://discuss.hashicorp.com/c/terraform-core/27) to discuss it.
