### ISSUE TITLE
how to create a spec describing blocks with only one label

### ISSUE THREAD

**Issue by gastrodon** [hashicorp/hcl#548]
Hello all! I'm having a little trouble defining an `hcldec.Spec` that describes a block with a single label, something like
```hcl
resource "named" {}
```

Specifically I'm having trouble understanding how the `LabelNames` field and `BlockLabelSpec` interact. A few examples can be reproduced with the same parsing code
```go
package main

import (
	"fmt"

	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/hashicorp/hcl/v2/hclparse"
)

var refSpec = ...

func main() {
	literal := []byte(`resource "foo" {}`)
	if file, diags := hclparse.NewParser().ParseHCL(literal, "file.hcl"); diags != nil {
		panic(diags)
	} else {
		if value, _, diags := hcldec.PartialDecode(file.Body, &refSpec, nil); diags != nil {
			panic(diags)
		} else {
			panic(fmt.Sprintf("%#v", value))
		}
	}
}
```

Given the following spec ([playground](https://go.dev/play/p/azhmiCLiAjY)), we get an error `Missing name for resource; All resource blocks must have 2 labels (name, name).`

```go
var refSpec = hcldec.BlockObjectSpec{
	TypeName:   "resource",
	LabelNames: []string{"name"},

	Nested: hcldec.ObjectSpec{
		"name": &hcldec.BlockLabelSpec{
			Name:  "name",
			Index: 0,
		},
	},
}
```

we get an error `Missing name for resource; All resource blocks must have 2 labels (name, name).`

If we drop the `LabelNames` field ([playground](https://go.dev/play/p/ulySp5KU_bC)), we get a panic
```
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/hashicorp/hcl/v2/hcldec.(*BlockObjectSpec).decode(0x7840c0, 0xc000102420, {0x0?, 0x0?, 0xc000167ea0?}, 0xc000167dd8?)
	/tmp/gopath2566431995/pkg/mod/github.com/hashicorp/hcl/v2@v2.13.0/hcldec/spec.go:1083 +0xce8
github.com/hashicorp/hcl/v2/hcldec.decode({0x661748, 0xc0001142c0}, {0x0, 0x0, 0x0}, 0x8?, {0x6616d8, 0x7840c0}, 0x1)
	/tmp/gopath2566431995/pkg/mod/github.com/hashicorp/hcl/v2@v2.13.0/hcldec/decode.go:21 +0x11d
github.com/hashicorp/hcl/v2/hcldec.PartialDecode(...)
	/tmp/gopath2566431995/pkg/mod/github.com/hashicorp/hcl/v2@v2.13.0/hcldec/public.go:26
main.main()
	/tmp/sandbox2234090471/prog.go:28 +0x145
```

If we instead keep the label names and drop the `BlockLabelSpec` ([playground](https://go.dev/play/p/5nYoqBQZVj7)), we get a value
```
cty.ObjectVal(map[string]cty.Value{"named":cty.EmptyObjectVal})
```

but since we don't know the value `named` until runtime I don't really find this to be useful - am I missing something here?

**Comment by gastrodon** [comment]
Okay, so I didn't realize that we are getting a `map[string]cty.Value` where each name points to a block - I had thought that the name value was going to populate some kind of `name` field.

More correct code here might involve using its `ElementIterator` to unmarshal all of the cty values in our map, and including its name ourselves

**Comment by apparentlymart** [comment]
Hi @gastrodon!

It sounds like you may have found an answer here but I'm just now seeing your question and wanted to add some extra notes in case they are useful to you or to someone else who finds this in future.

The main interesting quirk of the specification you shared here is that it combines `BlockObjectSpec` and `BlockLabelSpec` together in a single block. `BlockObjectSpec` implies introducing an additional label that will, once lowered to a `cty.Object` value, become the attribute name.

For example, a configuration like the following:

```hcl
resource "foo" "bar" {
}

resource "beep" "boop" {
}
```

... would decode into a data structure which would, if encoded as JSON just to view it, look like this:

```json
{
  "foo": {
    "name": "bar"
  },
  "beep": {
    "name": "boop"
  }
}
```

The first label of each block became an attribute name, while the second label became an attribute within the nested object. An important consequence of this result is that it would require all `resource` blocks in the given body to have unique strings as their first label: if there were two blocks starting with `resource "foo"` then they would collide with one another trying to populate the `foo` attribute and therefore decoding would fail.

You can avoid this requirement for a unique first label by using `BlockTupleSpec` instead, which yields a tuple (that is: a sequence where each element can be of a different type) of objects, with each object containing a pair of attributes to represent the two labels:

```go
var refSpec = hcldec.BlockTupleSpec{
	TypeName: "resource",

	Nested: hcldec.ObjectSpec{
		"type": &hcldec.BlockLabelSpec{
			Name:  "type",
			Index: 0,
		},
		"name": &hcldec.BlockLabelSpec{
			Name:  "name",
			Index: 1,
		},
	},
}
```

([Updated working Playground example](https://go.dev/play/p/UWvWZn9cMjy); I notice that the documentation for `BlockLabelSpec` doesn't mention that it's valid inside `BlockTupleSpec`, but that's just because we added `BlockTupleSpec` later and forgot to update the docs to mention it; all of the specs that decode HCL blocks can have ``BlockLabelSpec` nested inside them.)

A JSON serialization of the result of this one with the input I shared above would be the following instead:

```json
[
  {
    "type": "foo",
    "name": "bar"
  },
  {
    "type": "beep",
    "name": "boop"
  }
]
```

This structure doesn't require any of the labels to be unique across all objects, because it's producing a sequence of blocks instead of an object where each attribute needs a unique name.

Although this does work for the small empty block examples we've been discussing here, I do want to note that if your goal here is to decode a real Terraform configuration then I don't think you'll be able to do that with _just_ `hcldec`, because Terraform itself uses a more advanced decoding strategy with HCL's low-level API to allow it to partially-decode only the top-level `resource` blocks first, and then decodes each `resource` block with a separate `hcldec` schema. `hcldec` requires all blocks of a particular type to share the same schema, so there isn't any way to write a `hcldec` schema that can decode a whole `.tf` file in a single pass.
