### ISSUE TITLE
cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of

### ISSUE THREAD

**Issue by ajitk19** [hashicorp/hcl#572]
go/src/github.com/spf13/viper/internal/encoding/hcl/codec.go:8:2: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/usr/lib/go-1.10/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	/home/trisys/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)

**Comment by apparentlymart** [comment]
Hi @ajitk19,

It seems that you are using the Go toolchain in the obsolete "GOPATH mode". HCL is installable only in the modern "modules mode" because it has more than one major version and GOPATH mode cannot support that.

You are using an obsolete version of Go (1.10) which doesn't have support for the modern modules mode. You will need to upgrade to a newer version of Go to successfully use this library or any other library (like Viper) which depends on it. Go v1.11 is the minimum possible version that HCL v1.0 might be compatible with; this library is not compatible with any earlier version.

If upgrading isn't possible then you might instead discuss with the viper developers whether they intend to support such an old version of Go, and if so perhaps they would add some conditional build rules in their codebase to make the HCL features available only for Go 1.11 or later, while keeping the rest of that library available on Go v1.10.

But that would be a decision made by the maintainers of Viper rather than in this repository, so I'm going to close this issue. Thanks!
