### ISSUE TITLE
The message "The given key does not identify an element in this collection value" is not as helpful as it could be.

### ISSUE THREAD

**Issue by jonseymour** [hashicorp/hcl#591]
The message generated by this line:

    https://github.com/hashicorp/hcl/blob/main/ops.go#L171

and also other lines in that go source file are lacking a vital piece of information - which key is being talked about.

In cases where the dictionary is being accessed by a single direct reference with a literal key the answer will be obvious - it is the literal key itself. However, in cases where a dictionary is subject to access via an iteration variable across a dynamically composed collection of keys, the answer might not be so obvious. See for example: https://github.com/hashicorp/terraform/issues/27875

Or this one:

```
Error: Invalid index

  on ../../modules/config/ecs-view/main.tf line 13, in locals:
  13:   required = { for c, o in var.containers : c => { for k in lookup(o, "required_keys", []) : k => var.config.env[k] } }
    ├────────────────
    │ var.config.env is map of string with 153 elements

The given key does not identify an element in this collection value.
```

Yes, but which key exactly - it would be good to know.

Since HCL and Terraform do not provide any kind of try-catch pattern that allows the context of such exceptions to be reported close to source, it is often a very laborious process to manually construct the constituent collections to discover where, in fact, the mismatch occurred.

This job would be made roughly 10x easier if ops.go simply logged the key at issue -  a value that is readily available in the necessary execution context.

**Comment by apparentlymart** [comment]
Hi @jonseymour! Thanks for this feature request.

What you've seen here is the result of clumsily navigating a tension: Terraform has the concept of "sensitive values", which Terraform uses to track the heritage of a particular value and infer whether it should be obscured when displayed on-screen such as in an error message. But HCL itself doesn't know anything about this concept, and so can't take it into account when rendering error messages. To avoid HCL disclosing information that shouldn't be shown, HCL avoids including any specific values in the error message text it generates.

Terraform then attempts to compensate for this by generating the part of the error message which in your case appears as `var.config.env is map of string with 153 elements`. In lots of cases the key is also available in scope and so Terraform would also say something like `k is "foo"`. Because Terraform itself is the one generating those annotations, it can take into account its own concept of "sensitive" and so would avoid showing the value of `k` if it's a sensitive value.

It isn't yet clear to me why Terraform _didn't_ tell you what value `k` has in this case: the expression `var.config.env[k]` should have both `var.config.env` and `k` in scope and so Terraform should be able to see both of those in that context. If we can figure out why that isn't working here then we might be able to fix it by making that symbol visible to Terraform's error renderer.

With that in mind I'm going to initially classify this as a bug because it seems like Terraform should've been able to specify the value of `k` here, and so I'd like to try to fix that bug and make this work as intended. However, if we dig into this and realize that there's actually a good reason why that isn't working which I'm just not considering then we might need to think more creatively about other ways to deal with this within our existing architectural constraints, or by changing those architectural constraints.

Thanks again!

**Comment by apparentlymart** [comment]
It looks like that error message gets annotated with is evaluation context here:

https://github.com/hashicorp/hcl/blob/a514df9c5e5a496ea3cfe6c41a4304b2398f6bb7/hclsyntax/expression.go#LL931C15-L931C15

That `setDiagEvalContext` function really just assigns directly the evaluation context and expression into the diagnostic:

https://github.com/hashicorp/hcl/blob/a514df9c5e5a496ea3cfe6c41a4304b2398f6bb7/hclsyntax/diagnostics.go#L16-L23

...so this diagnostic should carry the information about what value `k` has because it's being annotated with the evaluation scope of the whole index expression, not just the collection being indexed.

The problem here might actually be up in Terraform rather than in HCL, but I'm not yet sure exactly what's going on.

https://github.com/hashicorp/terraform/blob/main/internal/command/views/json/diagnostic.go#L271-L277

Terraform seems to be calling `Expression.Variables` on the `IndexExpr` object, which should therefore see both `var.config.env` and `k` as direct variables in the main scope.

There is some logic in HCL's `Variables` function which filters out variables from child scopes:

https://github.com/hashicorp/hcl/blob/a514df9c5e5a496ea3cfe6c41a4304b2398f6bb7/hclsyntax/variables.go#L37-L46

...but I don't expect that to apply here because the expression we're saving in the diagnostic is in a context where `k` is in the _current_ scope, rather than in a child scope. (`k` would be in a child scope from the perspective of the whole `required` expression because the `for` expression declared it, but the index expression doesn't know that because it's _inside_ the `for` expression.)

Seems like there's some more digging to do here to understand why this isn't working quite right.

**Comment by apparentlymart** [comment]
Hi @jonseymour,

After reflecting on this some more I realize that the responsibility for showing this value belongs to Terraform rather than to HCL, because it's ultimately Terraform's job to package all of the diagnostics together and present them in its UI in an intelligible way.

Would you mind reopening this in the Terraform repository instead, so that the Terraform team can see it and prioritize it? The fix might involve some changes in this repository too, but that UI code belongs to Terraform so I think better for the Terraform team to debug it and figure out how best to fix it. Of course you could still link over here for the context we've already discussed.

Thanks!

**Comment by jonseymour** [comment]
Ok, thanks for the analysis. There is also a related open terraform issue (hashicorp/terraform#27875) which I have linked to this one. I'll leave that as the open issue for now and close this issue on the basis your analysis above. I may raise a separate issue at some later time.

**Comment by nemethloci** [comment]
I think this is still an issue. At least I'm facing this using terraform v1.9.8 and also neither this nor the referenced ticket seems to be linked to any MR/PR. @jonseymour Was this ever fixed?
