### ISSUE TITLE
`hcldec.Spec` not encoding in `go-plugin` due to `cty.Type` not having exported fields

### ISSUE THREAD

**Issue by mlund01** [hashicorp/hcl#592]
Was not sure where to put this issue, as it crosses 3 different libraries, but since the gobs for `Spec` types are registered in https://github.com/hashicorp/hcl/blob/main/hcldec/gob.go I think it makes sense to ask the question here. I am building something with hcl that utilizes `go-plugin`. I have a simple interface method in my plugin that I'd like to return a schema to be used inside of the calling application. The signature for this method is `InitSchema() (hcldec.ObjectSpec, error)`. The problem I'm running into is that my implementation of this method in the plugin utilizes the `hcldec.AttrSpec` type, which includes `cty.Type` as a field. Here is the example implementation,

```go
func (p *MyProvider) InitSchema() (hcldec.ObjectSpec, error) {
	return hcldec.ObjectSpec{
		"my-key": &hcldec.AttrSpec{
			Name: "my-key",
                        Type: cty.String,
			Required: true,
		},
	}, nil
}
```

When the calling application attempts to call it via `go-plugin`, I get the following error, `rpc: gob error encoding body: gob: type cty.Type has no exported fields`. I conceptually understand the issue. If `cty.Type` has no exported fields, it has nothing to serialize/deserialize between the calling application and the plugin, but given these types are registered with `encoding/gob`, along with the comments in the file suggesting it's explicitly done to use it in `go-plugin`, it appears they are meant to be used in such a way. Perhaps I'm misunderstanding something.

Thanks in advance for any suggestions or help!

**Comment by apparentlymart** [comment]
Hi @mlund01,

`hcldec` is not designed to allow directly serializing specs for use in a wire protocol. Although some of them could in principle be `gob`-encoded, to do so would cause your wire protocol to depend on implementation details that are not guaranteed and that might therefore break in future versions of HCL or its upstream dependency `cty`. (That's often the case for `gob` encoding unfortunately, because it essentially just writes the in-memory representation onto the wire, albeit with some encoding differences to make it platform-agnostic.)

This is an example of something that's outside of HCL's scope and that must be solved somehow in your calling application. For example, Terraform has a higher-level representation of schema used in its provider plugin wire protocol and then the client side (Terraform Core) lowers that to `hcldec` just before decoding; the higher-level schema representation is described as part of Terraform's protobuf schema. I believe Nomad took a similar approach but without quite so much abstraction on top of `hcldec`, and so its protocol has a more direct representation of a subset of the `hcldec` spec structure but still handles the conversion to a real spec client-side in the main Nomad engine.

Each application has some different needs for what exactly they intend to support and how tightly coupled they want to be to HCL. Terraform's protocol for example makes no assumption that the source configuration is coming from HCL aside from some concession to the "attributes vs. blocks" distinction, whereas Nomad's is tightly coupled to HCL and would presumably need an API breaking change if Nomad were to use something other than HCL in future. (Of course it's debatable whether that actually matters.)

I'd suggest following something like one of those examples for your application, depending on how tightly you want to couple to HCL's details.

**Comment by mlund01** [comment]
Thank you, I understand and appreciate the explanation. Separate but related question, what is the purpose of the gob registration for these types if they are not to be used over the wire? The description makes it seem very clear the registration is made specifically for go-plugin

**Comment by apparentlymart** [comment]
Back in the early days of developing what became Terraform v0.12 the Terraform team _tried_ to just smuggle all this new stuff over the existing `gob`-based plugin protocol. But that didn't really work for the reasons I described in my previous comment, and so we abandoned that strategy and created an entirely new protocol that was explicitly defined rather than relying on implementation details in Terraform as was true for the protocol of the time.

I think what you've found there are some leftover artifacts of that failed attempt. The timing of [the relevant commit](https://github.com/hashicorp/hcl/commit/f220c26836e2e4757b4ade3e46d54295139dc944) in mid-2017 matches when I was trying in vain to stuff all this new stuff through Terraform's existing plugin protocol so that it might gradually roll out as experimental features in v0.11.x releases, before eventually admitting defeat and resolving to do it all at once in v0.12.0 instead.

Modern go-plugin considers `encoding/gob` as a legacy protocol and prefers gRPC, so supporting `gob` for these wouldn't really help with correct modern use of that package anyway. We should probably remove those registrations, since (as you found before opening this issue) the underlying types don't support `gob` encoding anymore anyway.
