### ISSUE TITLE
Merge duplicate diagnostics to avoid diagnostics flood 

### ISSUE THREAD

**Issue by chenzejun** [hashicorp/hcl#674]
The below expr will return 50*50=2500 same diags, can we validate the expr first and return only one diag?
```
for i in range(50): length([for i in range(50):bad()])
```

**Comment by apparentlymart** [comment]
Hi @chenzejun,

Summarizing or aggregating diagnostics seems like a UI-level decision and so not in scope for the HCL library.

For example, HashiCorp Terraform already performs some aggregation of repetitive warning diagnostics in its own UI layer, and it does so just in time to render the diagnostics to print them. HCL contributes diagnostics to the set that Terraform is aggregating, but HCL does not have the full set of diagnostics at any point because it's the caller's (Terraform's) responsibility to gather diagnostics from various different operations and merge them together to return to the user. 

Although Terraform intentionally does not aggregate error diagnostics (a Terraform-level product design decision, not an HCL concern), any other application calling HCL is free to make a different decision about how to present diagnostics to its users, as part of its own UI layer.

Because presenting diagnostics to users is the responsibility of the calling application rather than of HCL itself directly, I'm going to close this. If you are working on or with another application that uses HCL then you might wish to send a separate feature request to the maintainers of that application, who could choose to implement filtering in their own application if they consider it a good user experience tradeoff.

Thanks!
