### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by strarsis** [hashicorp/hcl#81]
Is it possible to interpolate environment variables in HCL config?
An example would be very helpful.

Thank you and
with best regards

**Comment by sethvargo** [comment]
Hi @strarsis 

This is not possible directly with HCL, but can be implemented as a function by the tool you want to parse as HCL. See Terraform for an example. Thanks! :smile:

**Comment by kolis** [comment]
+1 for this as a feature request, would be useful in my consul-template config file

**Comment by skizot722** [comment]
+1 as well for this feature

**Comment by robsonpeixoto** [comment]
@sethvargo, Is it a desarable feature?
It's really useful in Consul template

**Comment by dkushner** [comment]
@sethvargo, for what its worth we also desperately need this to parameterize our vault deployments where our KV store is backed by Postgres.

**Comment by apparentlymart** [comment]
Hi all,

Thank you for the interest in using environment variables within the various applications that use HCL.

The code within this module deals only with the overall syntax of HCL. How the settings within the HCL structure are interpreted -- including any variables or functions that might be supported via interpolation/templates -- is the concern of the embedding applications.

In particular this means that supporting environment variables in consul-template and Vault would need to be feature requests to those respective applications, rather than to HCL itself. The teams for those applications are also in a better position to figure out how best to integrate environment variables support with other features they may have.
