### ISSUE TITLE
Printer/Formatter questions

### ISSUE THREAD

**Issue by VladRassokhin** [hashicorp/hcl#87]
Hi, after trying to implement printer behaviour in IntelliJ-HCL plugin, I've some questions related to hcl format:
In `comment_aligned.input` and `comment_aligned.output` some properties (1-3) have equals sign aligned, but 5,6 are not aligned with each other, so I'd expect something like
```hcl
	#deneme arslan
	fatih       = ["fatih"]  # yoo4
	#fatih arslan
	fatiharslan = ["arslan"] // yoo5
```
instead of 
```hcl
	#deneme arslan
	fatih = ["fatih"] # yoo4

	#fatih arslan
	fatiharslan = ["arslan"] // yoo5
```

As I understand one-line (with probably leading or same-line comment) properties grouped and have equals sign and same-line comment (if any) aligned. But that does not for properties with both leading and same-line comments. Looks like bug.

Also it would be nice to see some document which describes printer/formatter behaviour.

PS: Is there some communication channel to ask question about HCL/HIL instead of creating issues here?
//cc @fatih @mitchellh

**Comment by fatih** [comment]
Hi @VladRassokhin 

I'm not working anymore on HCL, but this was behavior was intended. Because there is comment for each of them. If you remove the comments you'll see that they align with each other. Of course this was based on my own preferences (and from Go's own preferences, and HCL is influenced from it). It's up to you guys to change the behavior. Formatting is hard, hope you find a middle ground :)
