### ISSUE TITLE
Pretty printer doesn't add quotes

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/hcl#95]
When using `hclfmt`, the following syntax is acceptable:

```
output foobar {}
```

I would have expected this to be corrected by the pretty pretty to include quotes around the resource name, i.e.

```
output "foobar" {}
```

**Comment by mitchellh** [comment]
We actually can't add quotes safely because what if the application intended it to be unquoted? They are semantically the same but stylistically different. For example, why wouldn't we do this:

```
"output" "foobar" {}
```

Or, in the TF resource case, what do we quote?

```
"resource" aws_instance "bar" {}
```

etc. See all the ambiguities? A schema-less printer can't know, so we mimic the user input.
